export interface ChangelogEntry {
  version: string
  date: string // ISO YYYY-MM-DD
  title: string
  items: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '6.13',
    date: '2026-09-04',
    title: 'Every Facility Back in the List',
    items: [
      'Fixed: newly created facilities — including The Fitzgerald of Palisades — could be missing from the facility list under the logo. If you own a franchise, the list was quietly being narrowed to that franchise even when you are the owner of the whole network',
      'The facility shown in the corner and the facility shown on the page are now always the same one. They used to be worked out two different ways, which is why the page could say one community while the corner said another',
      'Saved changes now show up straight away. Every "refresh this after you change it" instruction in the app was marking data as merely out-of-date rather than expired, so a new facility, a new invoice or a payroll change could still show the previous version for one more page load',
      'A stylist can no longer be saved without a facility. If one already was, Master Admin → Facilities now lists them and lets you put them where they work in one tap — a stylist saved this way appeared on no roster, in no Day Log and in no facility count, even though adding them looked like it worked',
      'Adding a stylist whose code is already taken now tells you who has it and offers to assign that person to this facility, instead of telling you to "assign them instead" with no way to do it',
      'The Apley demo now hands you back your own account when you finish or close it. Before, it left you signed in as the demo stylist for eight hours, which hid the facility list and the stylist pages',
      'Owner: Master Admin → Debug → "What the server sees" reports who you are recognised as, which facility you resolve to, and what your facility list should contain — and will tell you in plain words why a specific facility or stylist is not showing up',
      'Owner: restored access to the Stylist Directory, the applicant pipeline, several service actions and stylist working hours, which had quietly closed to the owner account',
    ],
  },
  {
    version: '6.12',
    date: '2026-09-03',
    title: 'Opening a New Community, Start to Finish',
    items: [
      'Adding a facility is now a guided setup instead of a form: name and code, salon days and hours, the stylists who work there (with their working days), the price list read straight off the community\'s price sheet, and how billing works — ending on a checklist and a printable QR sign-up poster you can hang the same afternoon',
      'Every new facility gets its own F-code automatically, so its family sign-up poster and signage work from the moment it exists — and the code is suggested but yours to change, with duplicate names and taken codes caught before you can submit',
      'You can now attach stylists you already have to a facility, several at once, and set the days each of them works right there — instead of one trip to each stylist\'s page. Their working days are what let families pick a day and what routes new requests',
      'Fixed: creating a facility could leave the corner of the screen showing one community while the page showed another. The facility name, the switcher and the page now always agree, and the switcher lists every active facility — including ones that arrived by import',
      'Fixed: a stylist added while you were on the Master Admin screen could be saved to no facility at all and then appear nowhere. New stylists now always land at the facility you are looking at',
      'Fixed: the facility list under the logo could not be scrolled to the bottom on smaller screens, hiding the last facilities and the "add facility" link',
      'Fixed: the Senior Stylist logo showed as a blank white block in the sidebar, on the family pages, and on the gift link',
      'Your facility spreadsheet is now an import: upload the CSV and communities that aren\'t in the app yet are created (with family sign-up switched on), while the ones that are get their billing type, revenue share, phone and address refreshed. Column order no longer matters',
      'Card charges at day close are now guaranteed to run before the page finishes its work, so a charge can no longer be dropped, and receipts go out by text as well as email for families who gave us a phone number',
      'Saving a card at the chair can now switch on automatic payment, but only when staff confirm the family asked for it — and the family still gets the notice telling them it happened',
      'Requests from families no longer get parked on one stylist: at a facility where nobody has hours set yet, a request stays unassigned so every stylist can see it',
      'Families can now see what each past visit cost, with the tip shown separately, and rows in the Day Log say "Card" or "Credit" in words instead of a small symbol',
      'Owner: Master Admin → Debug gained "Launch rehearsal", which prepares a practice facility and opens the family sign-up dry run — the click-through in docs/fitzgerald-walkthrough.md',
    ],
  },
  {
    version: '6.11',
    date: '2026-09-02',
    title: 'One QuickBooks Connection for Everyone',
    items: [
      'Connect QuickBooks once and every facility in the same QuickBooks company is connected — Master Admin → QuickBooks has a "Connect QuickBooks for all facilities" button, franchise owners get "Connect QuickBooks for all N" on their Franchise page, and any facility left out can be attached with one tap (no second Intuit sign-in)',
      'Detach vs disconnect: a facility can take itself off the shared connection from Settings → Billing without affecting anyone else; only the master can disconnect the whole company',
      'Nightly QuickBooks sync now pulls each company ONCE and hands every facility its own invoices and payments, instead of every facility re-reading the whole company — the same night covers 100+ facilities',
      'Sturdier: token refreshes are serialized so two servers can never invalidate each other, every create carries an Intuit request id so a dropped connection never makes a duplicate, and QuickBooks calls are metered against Intuit\'s per-company limit',
    ],
  },
  {
    version: '6.10',
    date: '2026-09-01',
    title: 'QuickBooks Safety Net',
    items: [
      'Paid means paid: an invoice a family already paid on the site (card, in-app, family portal, or salon credit) can no longer be re-opened by a QuickBooks sync — so the nightly automatic charge can never bill a card twice for the same visit',
      'Send via QB now skips residents on card-on-file autopay (they\'re charged on the site, not invoiced through QuickBooks) and tells you how many it skipped',
      'New Sync history in Settings → Billing & Payments → QuickBooks: every sync and every Send via QB is listed with a one-tap Undo — invoices are voided in QuickBooks (never deleted), anything already paid is left alone, and pulled payments or credits can be rewound',
      'Card payments collected on the site now show up in QuickBooks by themselves: every card-on-file charge, in-app card payment, and family-portal payment is recorded in QuickBooks as a payment applied to the same invoice (never twice — it checks QuickBooks first and caps at what the invoice still owes), and refunding one from the site voids it in QuickBooks too',
    ],
  },
  {
    version: '6.9',
    date: '2026-08-25',
    title: 'QuickBooks, Connected for Real',
    items: [
      'Connecting to QuickBooks now works from any address — the connect button always sends Intuit the one registered web address, so the "Uh oh, there\'s a connection problem" page from connecting via a different link is gone (one Intuit-side registration still required — see the checklist)',
      'New "Test connection" button in Settings → Billing → QuickBooks: one tap proves the whole connection works ("✓ Connected to {your company}") or tells you it needs a reconnect — with the reconnect link right there',
      '"Sync Customers" links every resident to their QuickBooks customer and creates any that are missing (as sub-customers under the facility, matching how the books are organized) — after that, invoices and payments match residents exactly instead of guessing by name',
      '"Send via QB" is live: pick a month and it creates real QuickBooks invoices from that month\'s completed, unpaid appointments — one per resident (or one facility invoice for facility-billed accounts), never double-billing an appointment already invoiced, tips never included — and can have QuickBooks email them',
      'Payments and credits recorded in QuickBooks now sync back too (with invoice sync, nightly once live sync is on) — payments you already recorded by check-scan or CSV import are recognized, never double-counted',
      'Sturdier under the hood: QuickBooks calls retry on rate limits, and disconnect/reconnect can no longer silently skip invoices that changed while disconnected',
    ],
  },
  {
    version: '6.8',
    date: '2026-08-18',
    title: 'Smoother Signup, Ready for Texting',
    items: [
      'The family sign-up now works like real pages: the phone\'s back gesture and the browser\'s back/forward buttons move between questions instead of leaving the wizard, and a page reload picks up right where the family left off (the password is always retyped — it\'s never saved)',
      'The sign-up phone field now shows the text-message agreement with a link to our Privacy Policy, and the policy gained a full "Text Messages" section — the paperwork carriers require before our Twilio texting number can go live',
      'Connect QuickBooks now opens Intuit in a new tab, so you never lose your place in Settings',
    ],
  },
  {
    version: '6.7',
    date: '2026-08-17',
    title: 'Salon Account — Sign In Your Way, Charged on Finalize',
    items: [
      'The family portal is now the "Salon Account" — one place for appointments, payments, transaction history, and account info. Families sign in with their EMAIL OR PHONE NUMBER plus a password they create right in the signup wizard (with a strength meter, show/hide, and confirm) — no more waiting on an email link to get started',
      'Phone-only families are fully supported: sign up with just a phone number, and once texting is on, a texted 6-digit code signs you in and appointment confirmations arrive by text (email families keep email — both when you have both)',
      'Charging is now automatic at day close: when a stylist finalizes the day log, the saved cards of autopay residents are charged for that day\'s unpaid completed visits — each visit is stamped paid immediately, so an edited and re-finalized day can never double-charge',
      'Scanned paper log sheets charge too — behind a human check: after importing a sheet, a "Charge cards" screen lists the matched autopay residents and nothing is charged until you review the names and press the button',
      'New shareable gift link: copy it from the resident\'s page (or "Share a gift link" on the family Billing page) and any relative can send salon credit — they see only the facility name and the resident\'s first name, never the account. Families see gifts land in the new "Payment history" section ("Gift from Michael — 50")',
      'Request dates now follow the stylist\'s schedule: all three request forms show which days the stylist works and block days nobody is there — and the stylist\'s request queue is ordered by the day (and time) each visit is wanted',
      'Fixed: real sign-up requests were sometimes auto-assigned to the tutorial\'s "Demo Sarah" and became invisible to every real stylist — assignments now only go to real stylists, and stranded requests were freed back into the queue',
      'Owner: the mobile Debug sheet gained the "Salon Account (demo)" login, and the signup preview banner now sits below the facility-name headline',
    ],
  },
  {
    version: '6.6',
    date: '2026-08-16',
    title: 'The Fitzgerald Package — Signup to First Charge',
    items: [
      'The family signup wizard got its owner-approved polish: your facility\'s name headlines every step, the first question is simply "Account Info", phone is required, and the marketing copy is gone — scan, answer, done',
      'Signing up now ALWAYS works on the spot: if we can\'t match the name to a resident on file, we create the resident right then and the account is live immediately. The facility sees a "New Family Account to Review" card in Settings — keep it, or one-tap merge it into an existing resident if it\'s a duplicate spelling',
      'After the review step, families land on a payment page: "Continue to Payment" saves a card (stored securely by Stripe — nothing is charged until a service happens) and automatic per-visit payment turns on. The first-login setup no longer re-asks for a card they already saved',
      'Money now reads the way the owners asked everywhere: "110" and "48.50" — no dollar signs, no ".00" clutter — across the app, the family portal, emails, and statements (spreadsheet exports unchanged)',
      'The family request page shows service names only (no prices), and requests can carry SEVERAL services — staff forms got a "＋ Add another service" row, and the stylist\'s Pick-time opens with every requested service already filled in',
      'The sign-up sheet\'s stylist dropdown is gone: the preferred DAY picks the stylist automatically (whoever is scheduled that day, lightest load first)',
      'Walk-in quick-create now takes the family\'s email and phone at the chair — with an email, the family automatically gets a "finish setting up your account" link',
    ],
  },
  {
    // R9 shipped as 6.4 first (2026-08-11); P53 renumbered to 6.5 — dates must
    // be STRICTLY increasing or readers of 6.4 never see the unread dot.
    version: '6.5',
    date: '2026-08-13',
    title: 'Onboarding-Ready — The Full Funnel, Hardened',
    items: [
      'Big scheduling change: facility admins and front desk now send appointment REQUESTS through the Sign-Up Sheet — only the stylist places the actual time slot. Clicking the calendar or the + button opens the request form; facility roles keep full calendar view, cancelling, and detail edits (service, price, notes, payment)',
      'The stylist\'s convert flow got smarter: requests open on the family\'s preferred date, their notes ("Mom likes it short") finally carry into the booking, and a brand-new facility with no hours entered no longer blocks the stylist from scheduling',
      'Fixed a long-standing availability bug: afternoon slots showed "no stylist available" and Sunday evenings counted as Monday because hours were checked against the wrong clock. Auto-assignment now uses the facility\'s own timezone',
      'Signup security hardened: the instant-connect check can no longer be passed with just a last name, look-alike resident names can\'t link a family to the wrong person, and lowercase QR links no longer 404',
      'Families now see their pending requests in the portal ("waiting for the salon to pick a time"), their salon credit ("$X available — the salon will apply it") so nobody pays twice, and appointment times in the facility\'s timezone',
      'Payments integrity: portal payments always run on the Senior Stylist platform account (a facility-entered Stripe key used to silently break payment recording), demo invoices can never absorb real money, and facility balances update the moment a family pays online',
      'Owner: the Debug tab\'s signup preview is now a true DRY RUN — the whole wizard including the confirmation screen, with nothing created and no emails sent (the old preview button opened the live wizard). Plus a new-facility runbook: docs/new-facility-runbook.md',
    ],
  },
  {
    version: '6.4',
    date: '2026-08-11',
    title: 'Fix It Where You See It',
    items: [
      'Misspelled resident name from a scanned sheet? Fix it right in the Day Log edit form — the new "Resident Name (fix spelling)" field updates the resident everywhere. Bookkeepers also get the full resident edit form on the resident\'s page now',
      'Bookkeepers and franchise admins can edit stylist codes (ST###) directly on the stylist\'s page — a code that\'s already taken is rejected with a clear message',
      'Your assistant learned both tricks too: "fix the spelling of Mrs. Smith\'s name to Adele Cohen" proposes the change and asks you to confirm',
    ],
  },
  {
    version: '6.3',
    // Dated a day after 6.2 (same-day releases from two streams) — dates must
    // be STRICTLY increasing or readers of 6.2 never see the unread dot.
    date: '2026-08-10',
    title: 'Scan, Sign Up, Done',
    items: [
      'Every family sign-up QR poster now works out of the box: self-signup is ON for all facilities by default (turn any single facility off in Settings → Family Portal). Owner: the Master Admin facilities tab has a one-tap "Turn on everywhere" button',
      'The signup wizard now recognizes residents: type a name that\'s on file and you\'ll see an "is this them?" card with the resident\'s name, room, and the family contact\'s initials — tap Yes and, if your name matches the family contact on file, your account connects INSTANTLY (no waiting for approval)',
      'Everything else still goes to the approval queue — but confirmed matches arrive pre-picked with a "Family confirmed the match" badge, so approving is one tap',
      'Approving a signup for a brand-new resident now CREATES the resident for you — name, room, and family contact filled straight from the request. No more separate add-resident step',
      'Fixed: approving a request that matched nobody used to silently create an account that could never sign in — that dead end is gone (the button now always links or creates a resident)',
      'A facility with signup off shows families a warmer message with the facility\'s name and a pointer to the front desk (in English and Spanish)',
    ],
  },
  {
    version: '6.2',
    date: '2026-08-09',
    title: 'Day Log + Separate Assistant Chats',
    items: [
      'The Daily Log is now simply the "Day Log" everywhere — sidebar, tabs, tutorials, exports, and emails. Same page, same features, shorter name',
      'Your assistant starts a fresh chat every time you open the app — no more old questions hanging around. Tap "Past chats" at the top of the chat window to reopen an earlier conversation, or "＋ New chat" to start over mid-conversation',
      'Past chats stay on your device only (the last 10) and are cleared when you sign out',
    ],
  },
  {
    version: '6.1',
    date: '2026-08-07',
    title: 'The Right View for Every Role',
    items: [
      'Payment at a glance: a small green card icon by a resident\'s name means they have a card on file, a blue coin means salon credit — you\'ll see them when booking, on daily-log rows, in the sign-up sheet, and in quick profiles. No icon = sort out payment at the chair',
      'Every role now lands on its best page at sign-in: facility admins open straight to their reports, franchise owners to the Franchise dashboard, bookkeepers to the Day Log — and the sidebar is reordered most-important-first per role, with a slimmer bottom section so there\'s more room to see your pages',
      'A real permissions cleanup: facilities can no longer see stylist commissions, pay, or personal details — the stylist list is now a simple roster (names, colors, schedule days), the directory and payroll are franchise/bookkeeper-side, and services are view-only for facility staff (bookkeepers and franchise owners manage the catalog). Franchise owners keep everything',
      'The billing page shows how each facility splits: how many residents are facility-billed vs individual payers, with each side\'s open balance. Set it per resident with the new Payment Type field (individual card/cash/check, facility-billed, or salon credit) — deeper per-type math comes next',
      'The assistant now talks like a personal assistant, not "AI" — the button says "Ask me anything" everywhere',
      'Signage gained a Family Sign-Up template: print the QR poster families scan to create their portal account, right from the Signage page (the Settings poster still works too)',
      'Debug tools (owner): impersonation views now run biggest-to-smallest (Franchise → Bookkeeper → Facility Admin → Front Desk → Stylist → Family), plus a new preview of the family sign-up wizard that works even before you turn self-signup on',
    ],
  },
  {
    version: '6.0',
    // NOTE: must be STRICTLY later than the previous entry's date — 5.8 and 5.9
    // share 2026-08-03, so anyone who read then would never see the unread dot.
    // This date also gates the one-time assistant announcement banner.
    date: '2026-08-05',
    title: 'Meet Your Assistant — Ask It Anything',
    items: [
      'Not sure where something is? Ask your assistant (the ✨ sparkle button, bottom-right on desktop, top bar on your phone): "where do I edit a service date?" or "how do I scan a log sheet?" — it answers with the exact steps for YOUR role',
      'It does things for you, too: "add a walk-in for Mrs. Smith, wash and set", "reschedule John to 2pm", "who still owes this month?" — it fills in the details and asks you to confirm before anything is saved',
      'Say "show me how" and it walks you through the actual screens step by step, pointing at the buttons like a coworker standing next to you',
      'Bookkeepers: you can now add and rename stylists yourselves (Stylists page in the sidebar — codes like ST825 are kept), and create a brand-new facility right from the scan screen\'s facility dropdown',
      'Scanning is sturdier: photos and PDFs are compressed automatically before upload (no more "Network Error" on big files), every page of a multi-page PDF is read, and typing in any service box filters the list as you type',
      'Exports now warn you if a selected facility ended up with no rows in the file, and Log Sheet History shows exactly how many bookings each sheet has on file',
    ],
  },
  {
    version: '5.9',
    date: '2026-08-03',
    title: 'New-Facility Onboarding — QR to Chair',
    items: [
      'The family signup page (from the QR poster) is now a gentle one-question-at-a-time wizard built for seniors: who you are, your name, the resident\'s name and room, email, phone — big text, big buttons, every optional step skippable',
      'Signups now tell you WHO they\'re for: the approval queue shows the resident\'s name, room, and relationship with a confidence badge, so approving is one glance instead of guesswork',
      'Applicants hear back: a "request received" email on signup, and a kind note if a request is declined; admins get a bell for every new signup',
      'Family appointment requests now land in the salon\'s Sign-Up Sheet queue — with a "From family portal" chip, the family\'s preferred dates and stylist, and a pending badge for admins and facility staff — instead of creating phantom calendar bookings nobody saw',
      'The family gets a real confirmation email the moment the stylist schedules their request — and the reminder checkboxes on the portal profile page actually control emails and texts now',
      'Families can turn automatic payment on or off themselves from the portal billing page (a saved card required, confirm step, email confirmation every time) — and everyone on the family\'s email list is notified whenever a card is saved or autopay changes',
      'Stylists can save a handed-over card right at the chair from any daily-log row — it goes straight into Stripe\'s secure form (camera scan works in the phone browser), charges nothing, and the family gets a "card saved" email',
      'New families\' first sign-in walks them through a one-time setup: save a card, opt into autopay, and pick a visit rhythm (weekly / every 2 weeks / monthly) — which feeds the salon\'s "due for a visit" list',
      'Fixed: families who signed up via the QR poster (with a different email than the one on file) could never request a sign-in link — now they can',
    ],
  },
  {
    version: '5.8',
    date: '2026-08-03',
    title: 'Know Exactly Who — Feedback Emails + Duplicate Logins',
    items: [
      'Every feedback submission now shows the exact email address (and account id) it came from — on the review page, and in the notification email you receive. Before, anyone with a name saved never showed their address anywhere',
      'Settings → Team flags a "Possible duplicate" when one person appears to have two logins (same name or email under two accounts) — with a tooltip explaining how to retire the unused one',
      'The "already linked to another team member" error now names the exact account holding the link, so you know which login to disconnect instead of guessing',
      'Fixed the real reason some stylists could never auto-link on sign-up: stylists who work at a facility through an assignment (rather than it being their home facility) were invisible to the automatic linker — invites and sign-ins now link them correctly',
    ],
  },
  {
    version: '5.7',
    date: '2026-08-01',
    title: 'Stylist Fix + QuickBooks Health at a Glance',
    items: [
      'Fixed a real blocker: if a stylist\'s login wasn\'t connected to their stylist record, the "Scan log sheet" and "Add walk-in" buttons simply vanished — so scanning a day log looked broken. The buttons now stay visible, explain why they\'re unavailable, and there\'s a one-tap "Ask my admin to link me" that instantly notifies your admins by bell and email',
      'Settings → Team now flags any teammate whose login isn\'t linked to a stylist record with an amber "Not linked" badge, so you can spot and fix it before anyone gets stuck',
      'Scan errors are honest now — a too-large photo or a timeout says exactly that instead of "network error"',
      'New QuickBooks status page for the owner (Master Admin → QuickBooks): every facility\'s connection, expense account, last sync, last import, and open balance in one grid, with anything needing attention flagged',
      'QuickBooks invoices can now sync automatically every night (turns on once Intuit approves the production app)',
      'Fixed a data-integrity bug in the QuickBooks sync: if a pull failed partway, it used to skip ahead anyway and silently miss every invoice that changed during the outage. It now only moves forward over data it actually received',
    ],
  },
  {
    version: '5.6',
    date: '2026-07-23',
    title: 'Answers You Can Tap — Live Typing, Smarter Search, Cleaner Mobile',
    items: [
      'The assistant now answers with real cards: ask "who owes the most?" or "what\'s today look like?" and you get a clean mini table or tiles under the reply — tap any person\'s name to pop open their profile',
      'Answers type out word-by-word as the AI writes them — no more waiting for the whole reply to appear at once',
      'Cmd+K (Ctrl+K) search and the assistant are now one team: type anything in the search palette and pick "✦ Ask the assistant" to send it straight to the AI — and the palette now works for every role',
      'Your phone got a cleaner top bar: a Search button and the AI sparkle now live in the header next to the bell — no more floating AI bubble covering your content (it still appears as the pulsing guide bubble during walkthroughs)',
      'Master admin: the mobile Debug button moved off the screen corner into the More menu; the amber Debug pill in the header opens it while you\'re impersonating',
      'The feedback bubble stayed right where it was',
    ],
  },
  {
    version: '5.5',
    date: '2026-07-23',
    title: 'Watch It Work — A Smarter, Friendlier Assistant',
    items: [
      'No more frozen "Thinking…" — the assistant now narrates as it works: "Checking the schedule…", "Crunching the numbers…", "Building your walkthrough…" swap live while it runs',
      'It never forgets your chat: the conversation survives page reloads and facility switches, and there\'s now a Stop button plus one-tap Retry when something fails',
      'The suggestion chips adapt to where you are — on the Day Log you\'ll see "Help me scan a sheet", on Billing "Who owes the most?" — and they stay visible while you chat',
      'New "☀️ My morning brief" chip: today\'s schedule, anything unpaid, and who\'s due for a visit in one tight summary',
      'Ask "who\'s due for a visit?" or "who has open time today?" — the assistant now finds residents overdue by their own visit rhythm and open gaps in stylists\' days, and offers to book them together',
      'Rate any answer 👍/👎 — feedback goes straight to the owner so the assistant keeps getting better; and a new "Meet your AI assistant" tour lives in the Help Center',
      'Cancelled the wrong appointment through the AI? The success toast now has one-tap Undo',
    ],
  },
  {
    version: '5.4',
    date: '2026-07-23',
    title: 'Your AI Coworker — It Walks You There',
    items: [
      'Ask "help me scan this sheet" or "take me to settings" and the assistant doesn\'t just explain — the chat shrinks to a small pulsing bubble, the app moves to the right page, and a spotlight + arrow lands on the exact button, step by step',
      'It fills fields for you as you go (you watch it type), and YOU perform every tap on the highlighted element — nothing happens without your finger on it, all on your real data',
      'Tap the pulsing bubble anytime to reopen the chat mid-walk — your whole conversation is still there; close the walk with the ✕ whenever you\'re done',
      'Works for every role, everywhere: scanning sheets, adding walk-ins and residents, booking, inviting teammates, sending statements, and more',
    ],
  },
  {
    version: '5.3',
    date: '2026-07-23',
    title: 'Your Assistant Remembers You',
    items: [
      'The AI now has a memory: tell it "remember I like money shown by month" or "call me Jo" and it saves that for you — permanently, across every chat. Say "forget that" any time, or ask "what do you remember about me?"',
      'Owner superpower: the master admin can say "remember for all stylists: …" or "remember for this facility: …" and every matching person\'s assistant follows that instruction immediately',
      'The AI also proposes its own learnings ("stylists often want their services logged for them") — these land on the Master Admin feedback page where the owner reviews each one, edits it, picks who it applies to (everyone, one facility, or one role), and approves or rejects it. Nothing spreads without approval.',
      'Role security tightened: anyone claiming permissions they don\'t have gets a firm, polite refusal — while the assistant stays fully capable within their real role. Only the owner account has network-wide access.',
    ],
  },
  {
    version: '5.2',
    date: '2026-07-23',
    title: 'The AI Knows Exactly Who You Are',
    items: [
      'Fixed the big one: if the owner account also belonged to a facility as an admin, the AI quietly treated you as just that facility\'s admin — "only a Master Admin can see network data" while you ARE the master admin. The owner is now ALWAYS the owner, network-wide, no matter what.',
      'The assistant now knows your name and exact role on every message — ask "who am I?" and it answers correctly, and it will never argue with you about your own permissions again',
      'If you\'re previewing the app as another role through Debug Mode, the AI knows that too and says so instead of acting confused',
    ],
  },
  {
    version: '5.1',
    date: '2026-07-23',
    title: 'Quick/Smart Switch + The AI Makes Things',
    items: [
      'New Quick | ✦ Smart switch right in the AI chat: Quick is fast and economical (the default), Smart thinks deeper for hard questions — your pick is remembered on your device',
      'Quick mode got a brain transplant: the assistant now always knows every role and what each person can do, every page of the app, and the money rules — so "what can a bookkeeper do?" or "where do I print the week?" answer instantly',
      'Ask it to MAKE things: "make me a closed-for-holiday sign for Friday" gives you a tap-to-open link with the sign ready to print; "create an invoice for Mrs. Hall" opens her printable statement built from real billing data',
      'Money answers now show the math — the period, the total, and what it breaks into',
      'Billing documents are always generated from QuickBooks-synced data — the AI never invents billing records and never sends anything without you',
    ],
  },
  {
    version: '5.0',
    date: '2026-07-22',
    title: 'The Assistant Sees Everything (Owner Edition)',
    items: [
      'Master admin: the assistant now covers your WHOLE network — "which facility owes us the most?" answers across every community, and you can act on any facility just by naming it: "book Mrs. Smith at Symphony Manor tomorrow at 10", "how much does F228 owe?"',
      'Say "switch me to Glen Meadow" and the app moves there — the facility switcher also now works properly for the owner account everywhere',
      'Real answers to "how do I…": the assistant has a built-in guide to every feature — ask how to scan a log sheet, set up the family portal, or run payroll and it walks you through step by step, with as much detail as you want',
      'Upgraded to a smarter AI model across the board — better at understanding shorthand, misspellings, and what you actually meant',
      'Every cross-facility change shows which community it lands in on the confirm card, and nothing ever saves without your tap',
    ],
  },
  {
    version: '4.9',
    date: '2026-07-22',
    title: 'Ask the AI to Do It',
    items: [
      'One AI everywhere: the Ask AI panel on Analytics and Master Admin is now the SAME full assistant as the sparkle button — it answers questions AND makes changes, with a confirm tap before anything is saved',
      '"Who owes us the most?" now names real residents with live balances, and "how much does Mrs. Hall owe?" pulls her full ledger — invoices, payments, and credits',
      'Tell it what to change: mark visits paid or no-show, add a tip, set a stylist\'s weekly hours, file or approve time off, add someone to the waitlist or sign-up sheet, create or reprice a service, update a room number or POA contact, send a receipt to the family',
      'Every role gets exactly their own powers — stylists manage their own day, front desk handles scheduling and residents, bookkeepers fix billing fields, the master admin can also read and reply to feedback by voice',
      'It understands messy asks: misspelled names get a "did you mean…?", brand-new residents are offered as a create, and relative times ("tomorrow at 10") resolve in your facility\'s timezone',
    ],
  },
  {
    version: '4.8',
    date: '2026-07-22',
    title: 'Supervisor Tools + Smarter Assistant + Mobile Polish',
    items: [
      "Admins, franchise admins, and the master admin can now set any stylist's weekly hours and file time off for them, right on the stylist's page (time off filed by a supervisor is pre-approved)",
      'The master admin can now do everything on stylist pages without impersonating: edit schedules, approve time off, verify compliance docs, send account invites',
      'Assistant upgrade: say "put Mrs. Smith in my next available slot" — it reads the real schedule, offers open times, and books the one you pick (always with a confirm tap)',
      'Big mobile fix: dialogs no longer get shoved off-screen when the keyboard opens (the cut-off New Pay Period bug), tall dialogs scroll instead of clipping, last rows never hide behind bars, and the scroll indicator finally lines up',
      'The getting-started checklist no longer covers the assistant and feedback buttons on phones',
    ],
  },
  {
    version: '4.7',
    date: '2026-07-21',
    title: 'Your AI Assistant + Pick Any Stylist',
    items: [
      'New AI assistant on every page (the sparkle button, bottom-right): ask about your schedule, residents, or numbers — or tell it to book, move, or cancel an appointment. It always asks you to confirm before anything changes. Type or talk.',
      'Booking dialog: you can now pick the stylist yourself — auto-assign stays the default, but "no stylist available" never blocks you again',
      'Fixed dialogs getting cut off behind the bottom bar on phones (Log Sheet History, Duplicates, and friends)',
      '"Who owes us the most?" now works for the master admin with a facility selected',
    ],
  },
  {
    version: '4.6',
    date: '2026-07-21',
    title: 'Stylists Unblocked & Feedback Replies',
    items: [
      'Stylists can now photograph and scan their own log sheet from the Day Log — every imported visit lands under their own name automatically',
      'Walk-ins fixed for stylists: adding a brand-new resident works again, and a new "➕ New service" option lets you add a missing service with its price right in the form',
      'Feedback is now a two-way street: the team can reply to your notes, you get a notification (and email), and replies live on the new My Feedback page',
    ],
  },
  {
    version: '4.5',
    date: '2026-07-15',
    title: 'Family Portal, Upgraded',
    items: [
      'Print a QR sign-up poster for your facility — families scan it and land on YOUR facility\'s sign-up, no choosing, no confusion',
      'New Portal Status panel: see who\'s connected, who can be invited, and invite every family with one tap',
      'Families can now add care preferences: style notes, allergies (shown to the stylist on the day log), a preferred stylist, visit rhythm, and reminder choices',
      'Merging duplicate residents now carries EVERYTHING to the kept resident — portal access, saved cards, billing history, photos — and the merge screen shows POA/Portal/Card badges with clear warnings first',
      'Apple Pay and Google Pay at the chair (after a one-time Stripe setting), plus "Make main card" on saved cards',
      'Link any family email to a resident directly from their page — existing accounts connect instantly',
    ],
  },
  {
    version: '4.4',
    date: '2026-07-15',
    title: 'Ask AI About Your Business',
    items: [
      'New "Ask AI" panel on Analytics (and Master Admin → Reports): ask plain-English questions like "Which facility owes us the most?" or "What was our best service last month?" and get answers computed from your real numbers',
      'Answers only ever come from your own data — revenue counts completed visits, and every figure says what period it covers',
      'Admins and bookkeepers see their facility; the master admin sees the whole network',
    ],
  },
  {
    version: '4.3',
    date: '2026-07-15',
    title: 'Accurate Earnings',
    items: [
      'Revenue now counts only COMPLETED visits — scheduled or cancelled appointments no longer inflate Analytics, dashboard tiles, totals, or exports',
      'Days now roll over on your facility\'s clock: an 8pm appointment shows on the right day in the day log and analytics, and the log no longer flips to tomorrow at 8pm Eastern',
      'Cancelling an appointment now removes it from Google Calendar and warns you when it was already marked paid',
      'Cancels and deletes made on spotty wifi sync automatically when you\'re back online',
    ],
  },
  {
    version: '4.2',
    date: '2026-07-14',
    title: 'Snappier Everywhere',
    items: [
      'Pages start loading the moment you tap — the offline system no longer sits in front of the network on every navigation',
      'Offline saving now happens quietly in the background and skips work when nothing changed — no more stutter while flipping calendar days or log dates',
      'The server does about half the work per page: your facility list and each resident\'s usual service are now remembered between pages',
      'Tutorial code no longer loads on every page — only when you actually run a tutorial',
      'Nothing about offline mode changed — same saved pages, same syncing, same privacy',
    ],
  },
  {
    version: '4.1',
    date: '2026-07-14',
    title: 'Stylist Privacy & Day-Log Fixes',
    items: [
      'Stylists now see only their own appointments and day log — walk-ins are locked to the signed-in stylist everywhere, including on the server',
      'Fixed the mobile day log: Done / No-show always respond (and tell you why if something fails), and the cramped service/price row is redesigned',
      'Delete an appointment by swiping its row or from the Edit form — with a confirm step',
      'Settings → Team: the Assign-stylist list now scrolls properly, and "Disconnect stylist" lets you unlink a login when someone switches emails',
      'Master admin can preview as a specific real stylist from the Debug tab — the preview now behaves exactly like that stylist\'s account',
    ],
  },
  {
    version: '4.0',
    date: '2026-07-12',
    title: 'Works Offline Everywhere',
    items: [
      'Nearly everything you do during a workday now saves offline and syncs later — sign-up sheets, waitlist, bookings from the calendar, day reschedules, and time-off requests join the existing walk-ins, edits, and photos',
      'The offline screen is now a real hub: today\'s schedule, your saved week, and a searchable resident roster',
      'Family members get their own offline card — next appointment and the facility phone number, in English or Spanish',
      'Offline storage grew from 1.5MB to 25MB and keeps a full week of saved copies',
      'The iPhone/iPad app opens to a branded retry screen instead of a browser error when launched with no signal',
    ],
  },
  {
    version: '3.9',
    date: '2026-07-12',
    title: 'Smoother & Smarter',
    items: [
      'Fixed the Master Admin page error — the access-request approval queue works again',
      'Master Admin facilities list can no longer be blanked by tutorial practice mode (and shows a clear banner + exit button when practice data is mixed in)',
      'Booking and walk-in forms pre-select each resident\'s usual service; one-tap tip presets',
      'Closing a half-filled booking or sign-up form now asks before discarding your typing',
      'Family portal: a big "Pay" button stays at your thumb when a balance is due, and the request form\'s submit button is always in reach',
      'Getting-started checklist gives you credit for signing up — you never start at 0%',
    ],
  },
  {
    version: '3.8',
    date: '2026-07-09',
    title: 'Faster Everywhere',
    items: [
      'Every page checks your login locally instead of calling out to the auth server — navigation is noticeably snappier',
      'Dashboard loads with one combined data request instead of seven separate ones',
      'Fonts now load from our own servers — no more waiting on Google Fonts',
      'Big screens (reports, booking form, scan review) download only when you open them',
      'Stylists can mark a visit done AND paid right on the home screen, with a one-tap jump to the Day Log',
    ],
  },
  {
    version: '3.7',
    date: '2026-07-07',
    title: 'Speed',
    items: [
      'Much faster app and site: background page-priming trimmed way down so it never competes with your taps',
      'Bottom tabs always switch — if a page is slow to respond, the app forces it through within seconds',
    ],
  },
  {
    version: '3.6',
    date: '2026-07-07',
    title: 'Bookkeeper Fixes & Self-Healing Updates',
    items: [
      'Fixed "Invalid input" blocking every daily-log edit (date, stylist, service, room, amount, tips)',
      'Switching facilities now actually switches the whole page, not just the label',
      'New facility picker right in the Day Log header — search by name or F-code',
      'After an app update, open tabs refresh themselves instead of showing a chunk error',
    ],
  },
  {
    version: '3.5',
    date: '2026-07-07',
    title: 'Stability & Tutorial Fixes',
    items: [
      'Fixed the outage: background page-warming no longer overloads the database',
      'Tutorials now exit demo mode instantly — on finish, on cancel, even if you close the tab mid-tour',
      "What's New opens as a proper dialog; fixed clipped toolbars on the dashboard",
      'Tutorials work at any time of day and auto-skip a step that fails to load instead of freezing',
    ],
  },
  {
    version: '3.4',
    date: '2026-07-07',
    title: 'Accessibility & Synced Tabs',
    items: [
      'Big accessibility pass for family members: screen-reader labels, announced errors, Spanish pronunciation, higher-contrast helper text',
      'Dialogs now keep keyboard focus inside and return it when closed',
      'Your customized bottom tabs now follow you across devices',
    ],
  },
  {
    version: '3.3',
    date: '2026-07-07',
    title: 'Full Offline Mode',
    items: [
      'Navigate between your pages while offline — recently visited screens keep working',
      'Photos taken offline upload automatically when wifi returns',
      'Walk-ins for brand-new residents now work offline too',
      'Cached pages are private per login and wiped on sign-out (shared-device safe)',
    ],
  },
  {
    version: '3.2',
    date: '2026-07-07',
    title: 'Mobile Comfort Pass & Offline Mode',
    items: [
      'Customize your bottom tabs — pick your 5 most-used, everything else lives under More',
      'Works offline: your schedule and day log show the last saved copy, and edits sync when wifi returns',
      'Offline banner shows pending changes and confirms when everything synced',
      'Bigger, easier tap targets across the app; dialogs open as bottom sheets on phones',
      'Fixed overlapping buttons and cramped headers on small screens',
    ],
  },
  {
    version: '3.1',
    date: '2026-07-07',
    title: 'Smart Scheduling, Health Scores & Spanish Portal',
    items: [
      'Family portal is now fully bilingual — EN/ES toggle in the header',
      '"Due for a visit" panel suggests residents based on their own visit rhythm',
      'Copy an entire salon day to a new date; print a weekly schedule',
      'Facility health score on Master Admin; invoice aging strip on Billing',
      'Booking style photos — snap from the day log, share to the family portal',
      'Stylists see a room-to-room route strip and a monthly earnings forecast',
      'Monthly statement email automation and appointment-reminder texts for families',
      'Prepay packages on the family portal (e.g. 3 × Wash & Set)',
    ],
  },
  {
    version: '3.0',
    date: '2026-07-07',
    title: 'Notifications, Waitlist & Payment Safeguards',
    items: [
      'In-app notification inbox with a bell in the header',
      'Cancellation waitlist — freed slots automatically alert the office',
      'Payment safeguards: auto-charge caps, double-pay protection, refunds, autopay consent emails',
      'Weekly owner digest email and resident birthday reminders',
      'Offline write-queue for spotty facility Wi-Fi; Tap to Pay groundwork',
    ],
  },
  {
    version: '2.9',
    date: '2026-06-22',
    title: 'Log Sheet History & Payment Types',
    items: [
      'Bookkeepers can now view, rename, move, and roll back imported OCR log sheets from the Day Log page',
      'Payment type now supports free-text (Cash, Check, Card, ACH, or custom) on all booking edits',
      'Bookkeeper log editing expanded: tips, payment method, date, resident, service, and delete',
    ],
  },
  {
    version: '2.8',
    date: '2026-06-17',
    title: 'OCR & Price Sheet Improvements',
    items: [
      'Bulk price sheet scanner now auto-detects facility from document content',
      'OCR review shows a proper dropdown for stylist selection (was invisible on most browsers)',
      'Fixed blank imports caused by empty service names in partial rows',
      'Send confirmation dialog before one-click emails and texts',
    ],
  },
  {
    version: '2.7',
    date: '2026-06-15',
    title: 'Family Portal Self-Signup & Authorization Hardening',
    items: [
      'Families can now request portal access directly from the facility login page',
      'Admins review and approve claim requests in Settings → Family Portal',
      'Welcome coupons automatically issued on first portal access',
      'Full authorization audit — closed cross-facility data leaks',
    ],
  },
  {
    version: '2.6',
    date: '2026-06-12',
    title: 'QuickBooks Import Suite & Billing Polish',
    items: [
      'Step 5 unapplied credits importer — import QB Customer Balance Detail CSV',
      'Batch memo scan: match check memo text to residents across all facilities at once',
      'Monthly billing view with by-resident / by-day toggle and CSV export',
      'Check image lightbox and "Match memo" assistant',
    ],
  },
  {
    version: '2.5',
    date: '2026-05-31',
    title: 'Interactive Scripted Tutorials',
    items: [
      'All 30+ help tours are now fully interactive — click through real workflows with demo data',
      'Mobile-specific tour variants for every role',
      'Onboarding checklist widget on the dashboard tracks your progress',
    ],
  },
  {
    version: '2.4',
    date: '2026-05-13',
    title: 'Mobile Layout & Tour Overhaul',
    items: [
      'Fixed iOS Safari layout shell — no more gap under the bottom nav',
      'Tour engine now uses SPA navigation — no page reloads between steps',
      'Stylist check-in with smart day-rescheduling (Phase 12T)',
      'CMD+K command palette for admins (Phase 12V)',
      'Resident and stylist peek drawer (Phase 12W)',
    ],
  },
  {
    version: '2.3',
    date: '2026-05-04',
    title: 'Service Log Import & Reconciliation',
    items: [
      'Import service log XLSX files directly into bookings with fuzzy facility/service matching',
      'Reconciliation queue for bookings that need a service linked',
      'Batch rollback of an entire import with one click',
      'Historical bookings show an "H" badge in the calendar and day log',
    ],
  },
]

/** ISO date string of the newest entry. */
export const LATEST_CHANGELOG_DATE = CHANGELOG[0]?.date ?? '2020-01-01'
