import type { ScriptedTour } from './scripted-tour-types'

export const BOOKKEEPER_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-bookkeeper-manual-entry',
    title: 'Add a Walk-in',
    scenarioSummary: 'Manually log a walk-in appointment for Mrs. Smith',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-add-walkin"]',
        route: '/log',
        title: 'Daily Log',
        description: 'Appointment not on the calendar? Log it here manually.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="daily-log-add-walkin"]',
        title: 'Click "Add Walk-in"',
        description: 'Opens the walk-in form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="walkin-resident-search"]',
        typeValue: 'Smith',
        advanceSelector: '[data-tour="walkin-resident-option"]',
        title: 'Pick the resident',
        description: 'We typed "Smith" for you. Click Mrs. Smith below to select her — or edit the search yourself.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="walkin-service-select"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Time and stylist default to now.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="walkin-submit"]',
        title: 'Log the walk-in',
        description: 'Click Add walk-in. A demo entry is created — not in real billing.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the walk-in entry in the Daily Log',
      'Selected a resident and service',
      'Logged the appointment manually',
    ],
  },
  {
    id: 'scripted-bookkeeper-getting-started',
    title: 'Getting Started',
    scenarioSummary: 'Walk your billing workflow, start to finish',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-scan-sheet"]',
        route: '/log',
        title: 'Start at the Daily Log',
        description: 'Your home base. Scan paper log sheets or add walk-ins — every service starts here.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-billing"]',
        title: 'Open Billing',
        description: 'Outstanding balances, check payments, and QB sync. Click Billing.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-outstanding"]',
        title: 'Track what is owed',
        description: 'Outstanding balances per resident. Record check payments and reconcile remittances here.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-payroll"]',
        title: 'Open Payroll',
        description: 'Pay periods auto-build from completed bookings. Click Payroll.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        title: 'Run payroll',
        description: 'Review each stylist, apply deductions, mark paid, and push to QuickBooks.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: "That's your workflow",
        description: 'Scan logs → record payments → reconcile → run payroll → export. The other tutorials walk each step.',
      },
    ],
    learnings: [
      'Scan logs and record payments',
      'Reconcile billing',
      'Run and export payroll',
    ],
  },
  {
    id: 'scripted-bookkeeper-scan-logs',
    title: 'Scanning Daily Logs',
    scenarioSummary: 'Scan a paper log sheet with OCR',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-scan-sheet"]',
        route: '/log',
        title: 'Scan Sheet button',
        description: 'Use this to scan a paper log sheet with your phone or flatbed scanner.',
      },
      {
        type: 'click',
        selector: '[data-tour="daily-log-scan-sheet"]',
        title: 'Open the scanner',
        description: 'Click Scan Sheet to open the OCR upload dialog.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="ocr-upload-area"]',
        title: 'Drop your scan',
        description: 'Upload a photo or PDF — Gemini reads the handwriting and extracts every appointment automatically.',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Review results',
        description: 'After scanning, each extracted row appears here — fix name mismatches, then click Import to create the bookings.',
      },
    ],
    learnings: [
      'Found the scan sheet button',
      'Opened the OCR upload',
      'Understood the review and import flow',
    ],
  },
  {
    id: 'scripted-bookkeeper-duplicates',
    title: 'Duplicate Resolution',
    scenarioSummary: 'Find and merge two demo profiles for Mrs. Smith',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: 'Residents list',
        description: 'OCR sometimes reads the same name differently — a resident ends up with two profiles. Notice the two "Smith" entries.',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-duplicates-button"]',
        title: 'Open Duplicates',
        description: 'Click Duplicates to see the auto-detected pairs.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="duplicates-pair-card"]',
        title: 'A duplicate pair',
        description: 'Same room, near-identical name. The system flags it for you to review side by side.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="duplicates-keep-btn"]',
        title: 'Choose which to keep',
        description: 'Click Keep A to make that the primary record. Its bookings stay; the other transfers in.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="duplicates-merge-btn"]',
        title: 'Merge them',
        description: 'Click Merge. The two profiles combine into one — all visits and billing follow.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the duplicates tool',
      'Understood how OCR creates duplicates',
      'Merged a duplicate pair',
    ],
  },
  {
    id: 'scripted-bookkeeper-billing-dashboard',
    title: 'Billing Dashboard',
    scenarioSummary: 'Explore the billing dashboard',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="billing-outstanding"]',
        route: '/billing',
        title: 'Outstanding balances',
        description: 'Residents with an unpaid balance appear here — amounts pulled from QB invoices.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-filters"]',
        title: 'Filters',
        description: 'Filter by date range, payment method, or facility to drill into specific payments.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-invoice-list"]',
        title: 'Payment records',
        description: 'Each check payment shows the resident breakdown and QB reconciliation status.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-send-statement"]',
        title: 'Send statement',
        description: "Email a monthly statement PDF to the facility's POA contact directly from here.",
      },
    ],
    learnings: [
      'Outstanding balances view',
      'Filtered payments',
      'Read payment records',
      'Sent a statement',
    ],
  },
  {
    id: 'scripted-bookkeeper-payroll',
    title: 'Payroll & Pay Periods',
    scenarioSummary: 'Review a pay period and mark it paid',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        route: '/payroll',
        title: 'Pay periods',
        description: 'Auto-generated from completed bookings — one per stylist per month.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-stylist-row"]',
        title: 'Earnings breakdown',
        description: 'Each row shows gross revenue, tips, commission rate, and net pay.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-mark-paid-btn"]',
        title: 'Mark as Paid',
        description: "Click Mark Paid when you've cut the check — it locks the pay period and prevents edits.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-export-btn"]',
        title: 'Export to QuickBooks',
        description: 'Push payroll directly to QuickBooks as a Bill with separate commission and tips line items.',
      },
    ],
    learnings: [
      'Found pay periods',
      'Read earnings breakdown',
      'Marked a period as paid',
      'Exported to QuickBooks',
    ],
  },
  {
    id: 'scripted-bookkeeper-export-logs',
    title: 'Export Daily Logs to Excel',
    scenarioSummary: 'Download a styled spreadsheet of daily log entries',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="log-export-excel"]',
        route: '/log',
        title: 'Export button',
        description: 'The Export button generates a styled .xlsx file matching the standard log sheet format.',
      },
      {
        type: 'click',
        selector: '[data-tour="log-export-excel"]',
        title: 'Click Export',
        description: 'Pick your date range and download. Columns match the paper log format your accountant expects.',
        placement: 'bottom',
      },
    ],
    learnings: [
      'Found the Excel export button',
      'Downloaded the styled spreadsheet',
    ],
  },
  {
    id: 'scripted-bookkeeper-quickbooks',
    title: 'QuickBooks Data',
    scenarioSummary: 'Connect QuickBooks and read invoice balances',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="billing-invoice-list"]',
        route: '/billing',
        title: 'QB invoices in Billing',
        description: 'Once QuickBooks is connected, invoices sync here automatically — balances stay in sync with QB.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-outstanding"]',
        title: 'Outstanding balances',
        description: 'Calculated from QB invoice data — always accurate to your live QuickBooks file.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-quickbooks"]',
        route: '/settings?section=billing',
        title: 'QB connection in Settings',
        description: 'Connect QuickBooks from Settings → Billing & Payments — each facility connects its own QB company.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-qb-connect-btn"]',
        title: 'Connect QuickBooks',
        description: "Click Connect to start the Intuit OAuth flow. You'll be back here in about 30 seconds.",
      },
    ],
    learnings: [
      'QB invoices sync to Billing',
      'Outstanding balances stay in sync',
      'Connect QB from Settings → Billing',
    ],
  },
  {
    id: 'scripted-bookkeeper-financial-reports',
    title: 'Financial Reports',
    scenarioSummary: 'Run and export financial reports',
    platform: 'desktop',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        route: '/analytics',
        title: 'Revenue analytics',
        description: 'Total revenue, appointment counts, and unpaid balance for any date range.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-date-range"]',
        title: 'Custom date range',
        description: 'Pick any month or custom period — compare quarters or run end-of-year reports.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-by-stylist"]',
        title: 'Per-stylist breakdown',
        description: 'Revenue and appointments per stylist — useful for commission verification.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-export-excel"]',
        title: 'Export',
        description: 'Download the styled spreadsheet for your accountant or year-end filing.',
      },
    ],
    learnings: [
      'Revenue analytics overview',
      'Custom date range',
      'Per-stylist breakdown',
      'Exported for accounting',
    ],
  },
  {
    // Mobile getting-started — the bottom nav exposes Log, Analytics, and Payroll
    // (Billing + QuickBooks have no mobile nav, so they're pointed to the website).
    id: 'scripted-bookkeeper-getting-started-mobile',
    title: 'Getting Started',
    scenarioSummary: 'Walk your mobile workflow, start to finish',
    platform: 'mobile',
    role: 'bookkeeper',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour-mobile="daily-log-scan-sheet"]',
        route: '/log',
        title: 'Start at the Daily Log',
        description: 'Your home base. Scan a paper log sheet or add a walk-in right from your phone.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-analytics"]',
        title: 'Tap Analytics',
        description: 'Revenue and stylist performance. Tap Analytics.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        title: 'Check the numbers',
        description: 'Revenue, appointment counts, and unpaid balance for any date range.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-payroll"]',
        title: 'Tap Payroll',
        description: 'Pay periods, ready to review. Tap Payroll.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        title: 'Review pay periods',
        description: 'Check earnings and mark periods paid.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Billing & QuickBooks on desktop',
        description: 'The billing dashboard and QuickBooks setup are on the full website. Open seniorstylist.com on a computer for those.',
      },
    ],
    learnings: [
      'Scan logs from your phone',
      'Check analytics and payroll',
      'Billing lives on the desktop site',
    ],
  },
]
