import type { ScriptedTour } from './scripted-tour-types'

export const MASTER_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-master-add-facility',
    title: 'Add a Facility',
    scenarioSummary: 'Create Sunrise of Denver as a practice facility',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'Your Facilities list',
        description: 'Every location you manage appears here.',
      },
      {
        type: 'click',
        selector: '[data-tour="master-add-facility-btn"]',
        title: 'Click "+ Create Facility"',
        description: 'Opens the new-facility form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="master-facility-form-name"]',
        typeValue: 'Sunrise of Denver',
        title: 'Name entered',
        description: "We typed the name. Use the facility's full legal name in practice. Click Next.",
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="master-facility-form-submit"]',
        title: 'Create the facility',
        description: 'Click Create Facility. A demo record is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Facilities list',
      'Created a new facility',
      'Ready to add staff and residents',
    ],
  },

  {
    id: 'scripted-master-add-stylist',
    title: 'Add a Stylist',
    scenarioSummary: 'Create a demo stylist in the directory',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists/directory',
        title: 'Stylist Directory',
        description: 'All stylists across your facilities live here.',
      },
      {
        type: 'click',
        selector: '[data-tour="directory-add-stylist-btn"]',
        title: 'Click "+ Add Stylist"',
        description: 'Opens the add-stylist form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="directory-add-stylist-name"]',
        typeValue: 'Alex Turner',
        title: 'Name entered',
        description: "We typed a demo name. Enter the stylist's real full name in practice. Click Next.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="directory-add-stylist-submit"]',
        title: 'Add the stylist',
        description: 'Click Add. Profile created — next: assign to a facility and set availability.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Stylist Directory',
      'Created a stylist profile',
      'Ready to assign to a facility',
    ],
  },

  {
    id: 'scripted-master-getting-started',
    title: 'Getting Started',
    scenarioSummary: 'Overview of Master Admin — facilities, reports, and franchises',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'Your facilities',
        description: 'Every location you manage appears here. Click any facility card to switch into its admin view.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-tab-reports"]',
        title: 'Reports tab',
        description: 'Click Reports to see a monthly revenue bar chart across all your facilities at once.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-tab-franchises"]',
        title: 'Franchises tab',
        description: 'Franchises group facilities under a common owner with shared stylist pools and super-admin access.',
      },
    ],
    learnings: [
      'Facilities overview',
      'Cross-facility reports',
      'Franchise management',
    ],
  },

  {
    id: 'scripted-master-applicant-pipeline',
    title: 'Applicant Pipeline',
    scenarioSummary: 'Review and promote applicants in the stylist pipeline',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists/directory',
        title: 'Stylist directory',
        description: 'All active stylists across every facility in one view.',
      },
      {
        type: 'click',
        selector: '[data-tour="directory-applicants-tab"]',
        title: 'Click Applicants',
        description: 'Switch to the applicant pipeline — your imported Indeed candidates.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="directory-applicants-list"]',
        title: 'Applicant pipeline',
        description: 'Each candidate shows location, status, and a Promote button to convert them to an active stylist.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the stylist directory',
      'Opened the applicant pipeline',
      'Ready to review and promote',
    ],
  },

  {
    id: 'scripted-master-quickbooks-setup',
    title: 'QuickBooks Setup',
    scenarioSummary: "Connect a facility's QuickBooks account",
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="settings-quickbooks"]',
        route: '/settings?section=billing',
        title: 'QuickBooks settings',
        description: "Each facility connects its own QuickBooks company. Switch facilities from the top to connect each one.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-qb-connect-btn"]',
        title: 'Connect button',
        description: "Click Connect QuickBooks — Intuit's OAuth flow opens. Takes about 30 seconds.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        route: '/payroll',
        title: 'Payroll after setup',
        description: 'Once connected, pay periods can be pushed directly to QuickBooks Bills with one click.',
      },
    ],
    learnings: [
      'Found QB settings',
      'Started the OAuth connection',
      'Ready to push payroll to QB',
    ],
  },

  {
    id: 'scripted-master-analytics',
    title: 'Cross-Facility Analytics',
    scenarioSummary: 'View revenue and performance across all facilities',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-tab-reports"]',
        route: '/master-admin',
        title: 'Master reports',
        description: "The Reports tab shows a monthly revenue bar chart across all facilities. Click it to load the chart.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        route: '/analytics',
        title: 'Facility analytics',
        description: "Drill into any facility's detailed analytics — revenue trends, appointment counts, and stylist breakdowns.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-by-stylist"]',
        title: 'Stylist breakdown',
        description: 'Revenue per stylist — identify top performers and compare across locations.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-export-excel"]',
        title: 'Export',
        description: "Export any facility's log data to a styled Excel spreadsheet for your accountant.",
      },
    ],
    learnings: [
      'Cross-facility revenue overview',
      'Facility-level analytics',
      'Per-stylist breakdown',
      'Excel export',
    ],
  },

  {
    id: 'scripted-master-franchise',
    title: 'Franchise Management',
    scenarioSummary: 'View and manage franchise groups',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'All your facilities',
        description: 'Facilities can be grouped into franchises — shared ownership, stylist pools, and reporting.',
      },
      {
        type: 'click',
        selector: '[data-tour="master-tab-franchises"]',
        title: 'Click Franchises',
        description: 'Switch to the Franchises tab to see your franchise groups.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-franchise-list"]',
        title: 'Franchise list',
        description: "Each franchise shows its member facilities and the owner's email. Click Edit to add/remove locations or change the owner.",
        placement: 'top',
      },
    ],
    learnings: [
      'Found franchise management',
      'Opened the Franchises tab',
      'Understood franchise structure',
    ],
  },

  {
    id: 'scripted-master-cross-facility-analytics',
    title: 'Cross-Facility Analytics',
    scenarioSummary: 'Compare revenue and KPIs across all your facilities',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-tab-reports"]',
        route: '/master-admin',
        title: 'Monthly report',
        description: 'The Reports tab compares total revenue and outstanding bookings across every facility for any month.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-outstanding"]',
        route: '/billing',
        title: 'Billing overview',
        description: 'Master billing shows outstanding balances across all facilities. Use the facility filter to drill in.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        route: '/analytics',
        title: 'Per-facility analytics',
        description: "Switch facilities at the top to see detailed revenue trends for each location.",
      },
    ],
    learnings: [
      'Cross-facility monthly report',
      'Billing overview across locations',
      'Per-facility deep analytics',
    ],
  },

  {
    id: 'scripted-master-merge-duplicates',
    title: 'Merging Duplicates',
    scenarioSummary: 'Merge duplicate facilities and residents',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'Duplicate facilities',
        description: 'The same location sometimes exists twice under slightly different names. The Merge tool finds and fixes these.',
      },
      {
        type: 'click',
        selector: '[data-tour="master-tab-merge"]',
        title: 'Click Merge',
        description: 'Opens the Merge tool with auto-detected duplicate facility pairs.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-merge-candidates"]',
        title: 'Merge candidates',
        description: 'Each pair shows a confidence score and resident/booking counts. Click Merge to consolidate — all data transfers safely.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Merge tool',
      'Understood duplicate detection',
      'Ready to merge facility pairs',
    ],
  },

  {
    id: 'scripted-master-team-roster',
    title: 'Global Team Roster',
    scenarioSummary: 'See every stylist and team member across your facilities',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists/directory',
        title: 'Global stylist directory',
        description: 'Every active stylist across all facilities — filter by status, sort by name, and view assignments.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="directory-applicants-tab"]',
        title: 'Applicant pipeline',
        description: 'The Applicants tab shows your hiring pipeline — imported from Indeed and ready to promote.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-team-section"]',
        route: '/settings?section=team',
        title: 'Facility-level users',
        description: 'Admins, facility staff, and bookkeepers are managed per-facility from Settings → Team.',
      },
    ],
    learnings: [
      'Global stylist directory',
      'Applicant pipeline',
      'Facility-level team management',
    ],
  },

  // ─── MOBILE TOURS ─────────────────────────────────────────────────────────
  // On a phone, master admin uses the standard admin bottom nav (Calendar, Log,
  // Residents, Analytics, Payroll, Settings). The master-only screens (Add
  // Facility, Franchises, Merge, Team Roster, Stylist Directory, QuickBooks
  // setup) have NO mobile nav entry, so these tours cover what IS reachable on
  // mobile and point to the full website for the deeper tools.
  {
    id: 'scripted-master-getting-started-mobile',
    title: 'Getting Started',
    scenarioSummary: 'A tour of everything you can do from your phone',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '',
        route: '/dashboard',
        title: 'Welcome, Lisa',
        description: 'On your phone you have the six tools you reach for most. Let me show you where each lives.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-calendar"]',
        title: 'Calendar',
        description: "Today's appointments across the facility. Tap + to add a booking on the go.",
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-daily-log"]',
        title: 'Daily Log',
        description: 'Every service performed today — review, scan paper sheets, or export.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-residents"]',
        title: 'Residents',
        description: 'Find and add residents at the selected facility.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-analytics"]',
        title: 'Analytics',
        description: 'Revenue, appointment counts, and per-stylist performance.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-payroll"]',
        title: 'Payroll',
        description: 'Review pay periods and mark them paid.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Deeper tools are on the website',
        description: 'Adding facilities, franchises, merging duplicates, the stylist directory, and QuickBooks setup live on the full site. Open seniorstylist.com on a computer for those.',
      },
    ],
    learnings: [
      'Where Calendar, Log, Residents, Analytics, and Payroll live',
      'Tap + on Calendar to book on the go',
      'Master-only tools are on the desktop site',
    ],
  },
  {
    id: 'scripted-master-calendar-mobile',
    title: 'Calendar',
    scenarioSummary: "Read today's schedule and book on the go",
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-calendar"]',
        route: '/dashboard',
        title: 'Calendar',
        description: 'Your facility schedule. Tap here any time to come back.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        title: 'Quick book',
        description: 'The + button opens a booking in seconds — pick a resident, service, and time.',
        placement: 'left',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Drag and rearrange on desktop',
        description: 'The full weekly grid — drag to reschedule, resize appointments — is best on a computer.',
      },
    ],
    learnings: [
      'Read the day on mobile',
      'Quick-book with the + button',
      'Full grid editing is on desktop',
    ],
  },
  {
    id: 'scripted-master-daily-log-mobile',
    title: 'Daily Log',
    scenarioSummary: 'Review what was done today',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-daily-log"]',
        route: '/log',
        title: 'Daily Log',
        description: 'Every completed service for the day, by stylist.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        title: 'A log entry',
        description: 'Each row is one appointment — resident, service, price, and payment status.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour-mobile="log-export-excel"]',
        title: 'Export to Excel',
        description: 'Download a styled spreadsheet matching your accounting format.',
        placement: 'bottom',
      },
    ],
    learnings: [
      'Read the daily log on mobile',
      'Understand a log entry',
      'Export logs to Excel',
    ],
  },
  {
    id: 'scripted-master-residents-mobile',
    title: 'Residents',
    scenarioSummary: 'Find and add residents from your phone',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-residents"]',
        route: '/residents',
        title: 'Residents',
        description: 'Everyone at the selected facility.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-search"]',
        title: 'Search',
        description: 'Type a name or room number to jump straight to a resident.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-new-button"]',
        title: 'Add a resident',
        description: 'Tap to add a new resident — name, room, and POA contact.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Imports & duplicates on desktop',
        description: 'Bulk CSV import and the duplicate-merge tool are on the full website.',
      },
    ],
    learnings: [
      'Find a resident fast',
      'Add a resident on mobile',
      'Bulk tools live on desktop',
    ],
  },
  {
    id: 'scripted-master-analytics-mobile',
    title: 'Analytics',
    scenarioSummary: 'Check revenue and performance on the go',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-analytics"]',
        route: '/analytics',
        title: 'Analytics',
        description: 'Revenue and appointment trends for the selected facility.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        title: 'Revenue summary',
        description: 'Total revenue, appointment count, and unpaid balance at a glance.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-date-range"]',
        title: 'Date range',
        description: 'Switch the month or pick a custom range.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Cross-facility view on desktop',
        description: 'Comparing all your facilities side by side is best on the full website.',
      },
    ],
    learnings: [
      'Read the revenue summary',
      'Change the date range',
      'Cross-facility analytics is on desktop',
    ],
  },
  {
    id: 'scripted-master-payroll-mobile',
    title: 'Payroll',
    scenarioSummary: 'Review pay periods and mark them paid',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-payroll"]',
        route: '/payroll',
        title: 'Payroll',
        description: 'Pay periods auto-generate from completed bookings.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        title: 'Pay periods',
        description: 'One per stylist per month — tap a period to see the earnings breakdown.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Mark paid & QuickBooks',
        description: "Open a period to see gross, tips, and net pay. Marking paid and pushing to QuickBooks work here too — the wider layout is easier on desktop.",
      },
    ],
    learnings: [
      'Find pay periods on mobile',
      'Read the earnings breakdown',
      'Mark a period paid',
    ],
  },
  {
    id: 'scripted-master-settings-mobile',
    title: 'Settings',
    scenarioSummary: 'Adjust facility settings from your phone',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-settings"]',
        route: '/settings',
        title: 'Settings',
        description: 'Facility details, hours, team, and integrations.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-working-hours"]',
        title: 'Working hours',
        description: 'Set the days and times your facility operates — these bound the booking slots.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Facilities, franchises & billing on desktop',
        description: 'Adding facilities, franchise management, merging duplicates, and QuickBooks setup are on the full website. Open it on a computer for those.',
      },
    ],
    learnings: [
      'Where facility settings live',
      'Set working hours',
      'Master-only setup is on desktop',
    ],
  },
]
