import type { ScriptedTour } from './scripted-tour-types'

export const FACILITY_STAFF_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-facility-staff-residents',
    title: 'Add a Resident',
    scenarioSummary: 'Add a new resident to your facility',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: 'Your Residents list',
        description: 'Everyone at your facility — visit history and balances in one place.',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-new-button"]',
        title: 'Click + to add a resident',
        description: 'Opens the new-resident form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="residents-add-name"]',
        typeValue: 'Eleanor Davis',
        title: 'Name entered',
        description: "We typed a demo name. Use the resident's full name in practice. Click Next.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-add-submit"]',
        title: 'Save the resident',
        description: 'Click Add. A demo resident is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Resident added',
        description: "They're in your list. Open their profile to add room number, POA contact, and notes.",
      },
    ],
    learnings: [
      'Found the Residents list',
      'Created a new resident',
      'Ready to add room, POA, and notes',
    ],
  },

  {
    id: 'scripted-facility-staff-scheduling-desktop',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: 'Click an open time slot',
        description: 'Click any open slot on the calendar to start a new booking.',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below. Click Next.',
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-resident-option"]',
        title: 'Click Mrs. Smith',
        description: 'Click her name to select her.',
        placement: 'right',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Price and duration filled automatically. Click Next.',
        placement: 'right',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am. A stylist is auto-assigned. Click Next.',
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Save the booking',
        description: 'Click Book Appointment. A demo booking is created — not on the real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form from the calendar',
      'Selected a resident, service, and time',
      'Stylist auto-assigned and appointment saved',
    ],
  },

  {
    id: 'scripted-facility-staff-scheduling-mobile',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'mobile',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        route: '/dashboard',
        title: 'Start a new booking',
        description: 'Tap the + button to open the booking form.',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below. Tap Next.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-resident-option"]',
        title: 'Tap Mrs. Smith',
        description: 'Tap her name to select her.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Price and duration filled automatically. Tap Next.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am. A stylist is auto-assigned. Tap Next.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Save the booking',
        description: 'Tap Book Appointment. A demo booking is created — not on the real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form',
      'Selected a resident, service, and time',
      'Stylist auto-assigned and appointment saved',
    ],
  },

  {
    id: 'scripted-facility-staff-signup-sheet',
    title: 'Use the Sign-Up Sheet',
    scenarioSummary: 'Log that Mrs. Smith wants a Wash & Set — no time slot needed',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-button"]',
        route: '/dashboard',
        title: 'Open the Sign-Up Sheet',
        description: "No time to pick a slot? Log the request here — a stylist will schedule it later.",
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below. Click Next.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-resident-option"]',
        title: 'Click Mrs. Smith',
        description: 'Click her name to select her.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-service"]',
        typeValue: 'Wash',
        title: 'Service searched',
        description: 'We searched for Wash & Set. Click it in the list.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-service-option"]',
        title: 'Select Wash & Set',
        description: 'Click to select the service.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-preferred-date"]',
        typeValue: '{{tomorrow}}',
        title: 'Preferred date set',
        description: 'We set tomorrow. Helps auto-assign the right stylist. Click Next.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-submit"]',
        title: 'Add to the sheet',
        description: 'Click Add to Sheet. A stylist will convert this into a real booking.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the Sign-Up Sheet',
      'Logged a resident, service, and preferred date',
      'Request queued for a stylist to schedule',
    ],
  },
]
