import type { ScriptedTour } from './scripted-tour-types'

export const STYLIST_MOBILE_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-stylist-getting-started-mobile',
    title: 'Getting Started',
    scenarioSummary: 'Walk your whole day, start to finish',
    platform: 'mobile',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour-mobile="stylist-mobile-booking-list"]',
        route: '/dashboard',
        title: "Today's appointments",
        description: 'This is your home screen — every appointment for today, in order. Tap a card to view details.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="checkin-banner"]',
        title: 'Check in when you arrive',
        description: "Tap “I'm Here” at the top. Running late? Your remaining appointments reshuffle automatically.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-daily-log"]',
        title: 'Tap Daily Log',
        description: 'After each visit you confirm it here. Tap Daily Log to see it.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        title: 'Confirm each visit',
        description: 'Mark the service done and set the payment status. At the end of the day, finalize the log.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-my-account"]',
        title: 'Tap Account',
        description: 'Your schedule, compliance documents, and time off live here. Tap Account.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="my-account-schedule"]',
        title: 'Your schedule & profile',
        description: 'Update your hours, upload your license and insurance, and request time off here.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour-mobile="mobile-home-logo"]',
        title: 'Back to your day',
        description: 'The Senior Stylist logo, top-left, always brings you home. Tap it.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '',
        title: "That's your whole day",
        description: 'Schedule → check in → log each visit → finalize. The other tutorials go deeper on each step.',
      },
    ],
    learnings: [
      'Read your daily appointment list',
      'Check in and confirm each visit',
      'Manage your schedule, compliance, and time off',
    ],
  },

  {
    id: 'scripted-stylist-calendar-mobile',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'mobile',
    role: 'stylist',
    steps: [
      {
        type: 'click',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        route: '/dashboard',
        title: 'Start a new booking',
        description: 'Tap the + button to open the booking form.',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below..',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-resident-option"]',
        title: 'Tap Mrs. Smith',
        description: 'Tap her name to select her.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Price and duration filled automatically..',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am..',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Save the booking',
        description: 'Tap Book Appointment. A demo booking is created — not on your real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form',
      'Selected a resident, service, and time',
      'Saved the appointment',
    ],
  },

  {
    id: 'scripted-stylist-daily-log-mobile',
    title: 'Daily Log',
    scenarioSummary: 'Mark Mrs. Smith as paid and finalize the day',
    platform: 'mobile',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Your Daily Log',
        description: "Mrs. Smith's appointment is here. Confirm visits and mark payment after each one.",
      },
      {
        type: 'click',
        selector: '[data-tour="log-payment-toggle"]',
        title: 'Tap the payment badge',
        description: 'Tap the $ badge to mark Mrs. Smith as paid.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="log-payment-toggle"]',
        title: 'Marked paid',
        description: 'Billing updates automatically. Your bookkeeper sees this in real time.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'Finalize the day',
        description: 'Tap Finalize Day to lock your log. Your admin and bookkeeper can see your completed day.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the appointment in the Daily Log',
      'Marked payment as paid',
      'Finalized the day',
    ],
  },

  {
    id: 'scripted-stylist-checkin-mobile',
    title: "I'm Here Check-In",
    scenarioSummary: 'Check in when you arrive at the facility',
    platform: 'mobile',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="checkin-banner"]',
        route: '/dashboard',
        title: 'Check-in banner',
        description: 'Appears on days you have appointments. Tap it when you arrive.',
      },
      {
        type: 'click',
        selector: '[data-tour="checkin-button"]',
        title: "Tap 'I'm Here →'",
        description: 'Records your arrival time against your first appointment.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour-mobile="stylist-mobile-booking-list"]',
        title: "You're checked in",
        description: 'Arrived late? We offer to shift your remaining appointments forward automatically.',
      },
    ],
    learnings: [
      'Found the check-in banner',
      'Recorded your arrival',
      'Learned about automatic late-arrival rescheduling',
    ],
  },

  {
    id: 'scripted-stylist-finalize-day-mobile',
    title: 'Finalize Your Day',
    scenarioSummary: 'Close out the daily log',
    platform: 'mobile',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Review before closing',
        description: 'Check payment status, notes, and any cancellations before you finalize.',
      },
      {
        type: 'click',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'Tap Finalize Day',
        description: "Locks today's log. Your admin and bookkeeper can now see your completed day.",
        placement: 'top',
      },
    ],
    learnings: [
      'Reviewed bookings before closing out',
      'Finalized the day',
    ],
  },
]
