import type { ScriptedTour } from './scripted-tour-types'

export const ADMIN_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-admin-residents',
    title: 'Add a Resident',
    scenarioSummary: 'Add a new resident to your facility',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: 'Your Residents list',
        description: 'Everyone at your facility — visit history and balances in one place.',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-new-button"]',
        title: 'Click + to add a resident',
        description: 'Opens the new-resident form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="residents-add-name"]',
        typeValue: 'Eleanor Davis',
        title: 'Name entered',
        description: "We typed a demo name. Use the resident's full name in practice. Click Next.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-add-submit"]',
        title: 'Save the resident',
        description: 'Click Add. A demo resident is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Resident added',
        description: "They're in your list. Open their profile to add room, POA contact, tip defaults, and portal access.",
      },
    ],
    learnings: [
      'Found the Residents list',
      'Created a new resident',
      'Ready to add room, POA, and portal access',
    ],
  },
  {
    id: 'scripted-admin-getting-started',
    title: 'Getting Started',
    scenarioSummary: 'Walk your facility workflow, start to finish',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: 'Your facility calendar',
        description: "Who's working today, coverage gaps, and every booking. Click any slot to create one. This is your daily home base.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="signup-sheet-button"]',
        title: 'Triage requests',
        description: 'Resident requests land here. Assign them to a stylist or schedule manually.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-residents"]',
        title: 'Open Residents',
        description: 'Service history, balances, and family portal access. Click Residents.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Your residents',
        description: 'Add residents, set up portal access, and track service history all from here.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-analytics"]',
        title: 'Open Analytics',
        description: 'Revenue, appointment counts, and stylist performance. Click Analytics.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        title: 'Track performance',
        description: 'Revenue and bookings for any date range — your monthly pulse on the facility.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-settings"]',
        title: 'Open Settings',
        description: 'Facility info, hours, team invites, and QuickBooks. Click Settings.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-facility-form"]',
        title: 'Configure your facility',
        description: 'Set hours and payment type, invite staff, and connect billing here. Specific tutorials cover each.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: "That's your workflow",
        description: 'Triage the day → manage residents → watch analytics → configure in Settings. Billing, payroll, and stylists live on the full site too.',
      },
    ],
    learnings: [
      'Run your daily dashboard',
      'Manage residents and requests',
      'Track analytics and configure your facility',
    ],
  },
  {
    id: 'scripted-admin-facility-setup',
    title: 'Facility Setup',
    scenarioSummary: 'Configure your facility name, hours, and billing',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="settings-facility-form"]',
        route: '/settings',
        title: 'Facility info',
        description: "Name, address, and timezone — keep these accurate so reports and notifications are correct.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-working-hours"]',
        title: 'Working hours',
        description: "These bounds block bookings outside your facility's service window.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-payment-type"]',
        title: 'Billing type',
        description: 'RFMS or IP billing determines how the billing dashboard organizes incoming payments.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-save-button"]',
        title: 'Save changes',
        description: 'Click Save anytime you update info. Changes take effect immediately.',
      },
    ],
    learnings: [
      'Updated facility info',
      'Set working hours',
      'Chose billing type',
      'Saved settings',
    ],
  },
  {
    id: 'scripted-admin-inviting-staff',
    title: 'Inviting Staff',
    scenarioSummary: 'Send an invite link to a staff member',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="settings-team-section"]',
        route: '/settings?section=team',
        title: 'Team settings',
        description: 'Everyone with access to your facility is listed here — admins, staff, bookkeepers, and stylists.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-invite-form"]',
        title: 'Invite form',
        description: 'Enter their email and pick a role: Admin, Facility Staff, Bookkeeper, or Stylist.',
      },
      {
        type: 'click',
        selector: '[data-tour="settings-invite-submit"]',
        title: 'Send the invite',
        description: "Click Send Invite — they'll receive an email with a link to set their password and log in.",
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-pending-invites"]',
        title: 'Pending invites',
        description: 'Sent invites appear here until accepted. Resend or cancel from this list.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Team section',
      'Composed an invite',
      'Sent it',
      'Tracked pending invitations',
    ],
  },
  {
    id: 'scripted-admin-reports',
    title: 'Reports & Analytics',
    scenarioSummary: 'Explore your analytics dashboard',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        route: '/analytics',
        title: 'Revenue summary',
        description: 'Month-to-date totals at the top — total revenue, appointments, and unpaid balance.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-date-range"]',
        title: 'Date range',
        description: 'Change to any month or custom range to compare periods side by side.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-by-stylist"]',
        title: 'Stylist breakdown',
        description: 'Revenue and appointment counts per stylist — identify your top performers.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-export-excel"]',
        title: 'Export to Excel',
        description: 'Download a styled spreadsheet matching your accounting log format.',
      },
    ],
    learnings: [
      'Revenue summary overview',
      'Adjusted date range',
      'Read per-stylist breakdown',
      'Exported a report',
    ],
  },
  {
    id: 'scripted-admin-family-portal',
    title: 'Family Portal',
    scenarioSummary: "Send a portal invite to Mrs. Smith's family",
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: 'Open a resident profile',
        description: "Click any resident's name to open their profile — that's where the Family Portal section lives.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="resident-portal-section"]',
        route: '/residents/{{mrs-smith}}',
        title: 'Family Portal section',
        description: 'Shows the POA contact email and portal status for this resident.',
      },
      {
        type: 'click',
        selector: '[data-tour="resident-portal-send-btn"]',
        title: 'Send the magic link',
        description: "Click Send Link — a one-click login email goes to the POA. No password required.",
        placement: 'bottom',
      },
    ],
    learnings: [
      'Opened a resident profile',
      'Found the Family Portal section',
      'Sent a portal invite',
    ],
  },
  {
    id: 'scripted-admin-compliance',
    title: 'Compliance Docs',
    scenarioSummary: "Check a stylist's license and insurance status",
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists',
        title: 'Stylists list',
        description: "Click any stylist's name to open their profile — compliance documents live there.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="stylist-compliance-section"]',
        route: '/stylists/{{demo-sarah}}',
        title: 'Compliance section',
        description: 'License and insurance certificates are listed here with expiry dates. Red = expired, amber = expiring soon.',
      },
    ],
    learnings: [
      'Found the stylists list',
      'Checked compliance documents and expiry status',
    ],
  },
  {
    id: 'scripted-admin-command-palette',
    title: 'Command Palette',
    scenarioSummary: 'Open the command palette with CMD+K',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="cmd-k-trigger"]',
        route: '/dashboard',
        title: 'Search icon in sidebar',
        description: 'Click the search icon — or press CMD+K — to open the command palette from anywhere.',
      },
      {
        type: 'click',
        selector: '[data-tour="cmd-k-trigger"]',
        title: 'Open it',
        description: 'Click to launch the palette. Type a resident name, stylist, or page to jump there instantly.',
        placement: 'right',
      },
    ],
    learnings: [
      'Found the command palette trigger',
      'Opened it with a click',
      'Can also use CMD+K from anywhere',
    ],
  },
  {
    id: 'scripted-admin-peek-drawer',
    title: 'Quick Profile Peek',
    scenarioSummary: 'Peek at a resident without leaving the log',
    platform: 'desktop',
    role: 'admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Click a resident name',
        description: 'Every resident name in the daily log is a link — click it to open a quick profile peek.',
      },
      {
        type: 'click',
        selector: '[data-tour="peek-resident-trigger"]',
        title: 'Click to peek',
        description: 'Click the resident name to open their profile in a side drawer.',
        placement: 'right',
      },
    ],
    learnings: [
      'Found the peek trigger in the daily log',
      'Opened a resident profile without navigating away',
      'Can also peek from billing and dashboard',
    ],
  },
]
