import type { ScriptedTour } from './scripted-tour-types'

export const FACILITY_STAFF_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-facility-staff-residents',
    title: 'Add a Resident',
    scenarioSummary: 'Add a new resident to your facility',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: 'Your Residents list',
        description: 'Everyone at your facility — visit history and balances in one place.',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-new-button"]',
        title: 'Click + to add a resident',
        description: 'Opens the new-resident form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="residents-add-name"]',
        typeValue: 'Eleanor Davis',
        title: 'Name entered',
        description: "We typed a demo name. Use the resident's full name in practice.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-add-submit"]',
        title: 'Save the resident',
        description: 'Click Add. A demo resident is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Resident added',
        description: "They're in your list. Open their profile to add room number, POA contact, and notes.",
      },
    ],
    learnings: [
      'Found the Residents list',
      'Created a new resident',
      'Ready to add room, POA, and notes',
    ],
  },

  {
    // P53 — the facility scheduling lockout: staff REQUEST appointments via the
    // Sign-Up Sheet; the stylist picks the actual time slot. The old
    // booking-modal chain is a stylist-side flow now.
    id: 'scripted-facility-staff-scheduling-desktop',
    title: 'Request an Appointment',
    scenarioSummary: 'Request a Wash & Set for Mrs. Smith — the stylist picks the time',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: 'Click anywhere on the calendar',
        description: 'Clicking a slot opens the Sign-Up Sheet — you log the REQUEST, and the stylist places it on their schedule.',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-resident"]',
        typeValue: 'Smith',
        advanceSelector: '[data-tour="signup-sheet-resident-option"]',
        title: 'Pick the resident',
        description: 'We typed "Smith" for you. Click Mrs. Smith below to select her — or edit the search yourself.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-service"]',
        typeValue: 'Wash',
        advanceSelector: '[data-tour="signup-sheet-service-option"]',
        title: 'Pick the service',
        description: 'We searched "Wash". Click Wash & Set in the list to select it.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-preferred-date"]',
        typeValue: '{{tomorrow}}',
        title: 'Preferred date set',
        description: 'We set tomorrow. The stylist sees this when picking the real time.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-submit"]',
        title: 'Add the request',
        description: 'Click Add to Sheet. The stylist converts it into a real time slot.',
        placement: 'top',
      },
    ],
    learnings: [
      'Requests go through the Sign-Up Sheet — stylists pick the times',
      'Logged a resident, service, and preferred date',
      'The stylist converts the request into a real booking',
    ],
  },

  {
    id: 'scripted-facility-staff-scheduling-mobile',
    title: 'Request an Appointment',
    scenarioSummary: 'Request a Wash & Set for Mrs. Smith — the stylist picks the time',
    platform: 'mobile',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        route: '/dashboard',
        title: 'Start a request',
        description: 'Tap the + button — it opens the Sign-Up Sheet. You log the request; the stylist picks the time.',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-resident"]',
        typeValue: 'Smith',
        advanceSelector: '[data-tour="signup-sheet-resident-option"]',
        title: 'Pick the resident',
        description: 'We typed "Smith" for you. Tap Mrs. Smith below to select her — or edit the search yourself.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-service"]',
        typeValue: 'Wash',
        advanceSelector: '[data-tour="signup-sheet-service-option"]',
        title: 'Pick the service',
        description: 'We searched "Wash". Tap Wash & Set in the list to select it.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-preferred-date"]',
        typeValue: '{{tomorrow}}',
        title: 'Preferred date set',
        description: 'We set tomorrow. The stylist sees this when picking the real time.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-submit"]',
        title: 'Add the request',
        description: 'Tap Add to Sheet. The stylist converts it into a real time slot.',
        placement: 'top',
      },
    ],
    learnings: [
      'Requests go through the Sign-Up Sheet — stylists pick the times',
      'Logged a resident, service, and preferred date',
      'The stylist converts the request into a real booking',
    ],
  },

  {
    id: 'scripted-facility-staff-signup-sheet',
    title: 'Use the Sign-Up Sheet',
    scenarioSummary: 'Log that Mrs. Smith wants a Wash & Set — no time slot needed',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-button"]',
        route: '/dashboard',
        title: 'Open the Sign-Up Sheet',
        description: "No time to pick a slot? Log the request here — a stylist will schedule it later.",
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-resident"]',
        typeValue: 'Smith',
        advanceSelector: '[data-tour="signup-sheet-resident-option"]',
        title: 'Pick the resident',
        description: 'We typed "Smith" for you. Click Mrs. Smith below to select her — or edit the search yourself.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-service"]',
        typeValue: 'Wash',
        advanceSelector: '[data-tour="signup-sheet-service-option"]',
        title: 'Pick the service',
        description: 'We searched "Wash". Click Wash & Set in the list to select it.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-preferred-date"]',
        typeValue: '{{tomorrow}}',
        title: 'Preferred date set',
        description: 'We set tomorrow. Helps auto-assign the right stylist.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-submit"]',
        title: 'Add to the sheet',
        description: 'Click Add to Sheet. A stylist will convert this into a real booking.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the Sign-Up Sheet',
      'Logged a resident, service, and preferred date',
      'Request queued for a stylist to schedule',
    ],
  },

  {
    id: 'scripted-staff-getting-started',
    title: 'Getting Started',
    scenarioSummary: 'Walk your front-desk workflow, start to finish',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: "Your facility's calendar",
        description: "Every stylist's bookings at your facility, all in one place. This is your home base.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="signup-sheet-button"]',
        title: 'Take a request',
        description: 'When a resident asks for an appointment, log it here — the system auto-assigns the right stylist by date and service.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-residents"]',
        title: 'Open Residents',
        description: 'Look up and update residents. Click Residents.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Your residents',
        description: 'Names, rooms, and POA contacts. Add new residents as they move in, and update profiles here.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-daily-log"]',
        title: 'Open the Day Log',
        description: 'See the day unfold. Click Day Log.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        title: 'Monitor the day',
        description: "Watch services get logged in real time — read-only for you, but a great end-of-day check that everything looks right.",
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: "That's your workflow",
        description: 'Take requests → book on the calendar → keep residents current → review the log. The other tutorials go deeper on each.',
      },
    ],
    learnings: [
      'Take requests and book appointments',
      'Look up and update residents',
      'Review the day log',
    ],
  },

  {
    id: 'scripted-staff-daily-log',
    title: 'The Day Log',
    scenarioSummary: "Read today's appointments in the day log",
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: "Today's appointments",
        description: 'Every service logged today — stylist, resident, service, and payment status.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="log-payment-toggle"]',
        title: 'Payment status',
        description: 'Each entry shows whether the service is paid, invoiced, or waived — set by the stylist.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="peek-resident-trigger"]',
        title: 'Peek at a resident',
        description: "Click any resident name to see their visit history and notes without leaving this page.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'Finalize button',
        description: "At end of day the stylist or admin locks the log. You'll see a green checkmark when it's done.",
      },
    ],
    learnings: [
      "Read today's day log",
      'Understood payment status',
      'Peeked at a resident profile',
      'Learned about finalization',
    ],
  },

  {
    id: 'scripted-staff-daily-log-readonly',
    title: 'Day Log (Read-Only)',
    scenarioSummary: "Monitor today's services as facility staff",
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Facility staff view',
        description: 'You can see every appointment logged today — service, resident, stylist, and amount. All read-only.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="peek-resident-trigger"]',
        title: 'Peek at a resident',
        description: 'Click any resident name for a quick profile view — last visits, notes, and contact info.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'End-of-day finalization',
        description: "The Finalize button locks the day's log. Only admins and stylists can finalize.",
      },
    ],
    learnings: [
      'Monitored the day log as facility staff',
      'Peeked at a resident profile',
      'Understood the finalization step',
    ],
  },
]
