import type { ScriptedTour } from './scripted-tour-types'

export const MASTER_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-master-add-facility',
    title: 'Add a Facility',
    scenarioSummary: 'Create Sunrise of Denver as a practice facility',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'Your Facilities list',
        description: 'Every location you manage appears here.',
      },
      {
        type: 'click',
        selector: '[data-tour="master-add-facility-btn"]',
        title: 'Click "+ Create Facility"',
        description: 'Opens the new-facility form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="master-facility-form-name"]',
        typeValue: 'Sunrise of Denver',
        title: 'Name entered',
        description: "We typed the name. Use the facility's full legal name in practice.",
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="master-facility-form-submit"]',
        title: 'Create the facility',
        description: 'Click Create Facility. A demo record is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Facilities list',
      'Created a new facility',
      'Ready to add staff and residents',
    ],
  },

  {
    id: 'scripted-master-add-stylist',
    title: 'Add a Stylist',
    scenarioSummary: 'Create a demo stylist in the directory',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists/directory',
        title: 'Stylist Directory',
        description: 'All stylists across your facilities live here.',
      },
      {
        type: 'click',
        selector: '[data-tour="directory-add-stylist-btn"]',
        title: 'Click "+ Add Stylist"',
        description: 'Opens the add-stylist form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="directory-add-stylist-name"]',
        typeValue: 'Alex Turner',
        title: 'Name entered',
        description: "We typed a demo name. Enter the stylist's real full name in practice.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="directory-add-stylist-submit"]',
        title: 'Add the stylist',
        description: 'Click Add. Profile created — next: assign to a facility and set availability.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Stylist Directory',
      'Created a stylist profile',
      'Ready to assign to a facility',
    ],
  },

  {
    id: 'scripted-master-getting-started',
    title: 'Getting Started',
    scenarioSummary: 'Walk your platform control center, start to finish',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="nav-master-admin"]',
        route: '/master-admin',
        title: 'Open Master Admin',
        description: 'Your platform control center. Click Master Admin in the sidebar.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        title: 'Every facility',
        description: 'All your locations, with applicants and access requests across the whole platform. Click any card to manage it.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="master-tab-reports"]',
        title: 'Open Reports',
        description: 'Cross-facility revenue at a glance. Click the Reports tab.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-tab-franchises"]',
        title: 'Franchises',
        description: 'Group facilities under a franchise owner with shared stylist pools and super-admin access.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: "That's your control center",
        description: 'Facilities → applicants → reports → franchises → merge tools. Add facilities, the stylist directory, and QuickBooks each have their own tutorial.',
      },
    ],
    learnings: [
      'Open and read Master Admin',
      'Manage facilities and applicants',
      'Cross-facility reports and franchises',
    ],
  },

  {
    id: 'scripted-master-applicant-pipeline',
    title: 'Applicant Pipeline',
    scenarioSummary: 'Review and promote applicants in the stylist pipeline',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists/directory',
        title: 'Stylist directory',
        description: 'All active stylists across every facility in one view.',
      },
      {
        type: 'click',
        selector: '[data-tour="directory-applicants-tab"]',
        title: 'Click Applicants',
        description: 'Switch to the applicant pipeline — your imported Indeed candidates.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="directory-applicants-list"]',
        title: 'Applicant pipeline',
        description: 'Each candidate shows location, status, and a Promote button to convert them to an active stylist.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the stylist directory',
      'Opened the applicant pipeline',
      'Ready to review and promote',
    ],
  },

  {
    id: 'scripted-master-quickbooks-setup',
    title: 'QuickBooks Setup',
    scenarioSummary: "Connect a facility's QuickBooks account",
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="settings-quickbooks"]',
        route: '/settings?section=billing',
        title: 'QuickBooks settings',
        description: "Each facility connects its own QuickBooks company. Switch facilities from the top to connect each one.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-qb-connect-btn"]',
        title: 'Connect button',
        description: "Click Connect QuickBooks — Intuit's OAuth flow opens. Takes about 30 seconds.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        route: '/payroll',
        title: 'Payroll after setup',
        description: 'Once connected, pay periods can be pushed directly to QuickBooks Bills with one click.',
      },
    ],
    learnings: [
      'Found QB settings',
      'Started the OAuth connection',
      'Ready to push payroll to QB',
    ],
  },

  {
    id: 'scripted-master-analytics',
    title: 'Facility Analytics',
    scenarioSummary: "Drill into one facility's revenue, appointments, and stylists",
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        route: '/analytics',
        title: 'Facility analytics',
        description: "The currently selected facility's numbers — revenue trends, appointment counts, and stylist breakdowns for any date range.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-by-stylist"]',
        title: 'Stylist breakdown',
        description: 'Revenue per stylist — identify top performers and compare across locations.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-export-excel"]',
        title: 'Export',
        description: "Export any facility's log data to a styled Excel spreadsheet for your accountant.",
      },
    ],
    learnings: [
      'Facility-level analytics',
      'Per-stylist breakdown',
      'Excel export',
    ],
  },

  {
    id: 'scripted-master-franchise',
    title: 'Franchise Management',
    scenarioSummary: 'View and manage franchise groups',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'All your facilities',
        description: 'Facilities can be grouped into franchises — shared ownership, stylist pools, and reporting.',
      },
      {
        type: 'click',
        selector: '[data-tour="master-tab-franchises"]',
        title: 'Click Franchises',
        description: 'Switch to the Franchises tab to see your franchise groups.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-franchise-list"]',
        title: 'Franchise list',
        description: "Each franchise shows its member facilities and the owner's email. Click Edit to add/remove locations or change the owner.",
        placement: 'top',
      },
    ],
    learnings: [
      'Found franchise management',
      'Opened the Franchises tab',
      'Understood franchise structure',
    ],
  },

  {
    id: 'scripted-master-cross-facility-analytics',
    title: 'Cross-Facility Analytics',
    scenarioSummary: 'Compare revenue and KPIs across all your facilities',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-tab-reports"]',
        route: '/master-admin',
        title: 'Monthly report',
        description: 'The Reports tab compares total revenue and outstanding bookings across every facility for any month.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="billing-outstanding"]',
        route: '/billing',
        title: 'Billing overview',
        description: 'Master billing shows outstanding balances across all facilities. Use the facility filter to drill in.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        route: '/analytics',
        title: 'Per-facility analytics',
        description: "Switch facilities at the top to see detailed revenue trends for each location.",
      },
    ],
    learnings: [
      'Cross-facility monthly report',
      'Billing overview across locations',
      'Per-facility deep analytics',
    ],
  },

  {
    id: 'scripted-master-merge-duplicates',
    title: 'Merging Duplicates',
    scenarioSummary: 'Merge duplicate facilities and residents',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="master-facility-list"]',
        route: '/master-admin',
        title: 'Duplicate facilities',
        description: 'The same location sometimes exists twice under slightly different names. The Merge tool finds and fixes these.',
      },
      {
        type: 'click',
        selector: '[data-tour="master-tab-merge"]',
        title: 'Click Merge',
        description: 'Opens the Merge tool with auto-detected duplicate facility pairs.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="master-merge-candidates"]',
        title: 'Merge candidates',
        description: 'Each pair shows a confidence score and resident/booking counts. Click Merge to consolidate — all data transfers safely.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the Merge tool',
      'Understood duplicate detection',
      'Ready to merge facility pairs',
    ],
  },

  {
    id: 'scripted-master-team-roster',
    title: 'Global Team Roster',
    scenarioSummary: 'See every stylist and team member across your facilities',
    platform: 'desktop',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylists-table"]',
        route: '/stylists/directory',
        title: 'Global stylist directory',
        description: 'Every active stylist across all facilities — filter by status, sort by name, and view assignments.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="directory-applicants-tab"]',
        title: 'Applicant pipeline',
        description: 'The Applicants tab shows your hiring pipeline — imported from Indeed and ready to promote.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-team-section"]',
        route: '/settings?section=team',
        title: 'Facility-level users',
        description: 'Admins, facility staff, and bookkeepers are managed per-facility from Settings → Team.',
      },
    ],
    learnings: [
      'Global stylist directory',
      'Applicant pipeline',
      'Facility-level team management',
    ],
  },

  // ─── MOBILE TOURS ─────────────────────────────────────────────────────────
  // On a phone, master admin uses the standard admin bottom nav (Calendar, Log,
  // Residents, Analytics, Payroll, Settings). The master-only screens (Add
  // Facility, Franchises, Merge, Team Roster, Stylist Directory, QuickBooks
  // setup) have NO mobile nav entry, so these tours cover what IS reachable on
  // mobile and point to the full website for the deeper tools.
  {
    id: 'scripted-master-getting-started-mobile',
    title: 'Getting Started',
    scenarioSummary: 'Walk through your phone — tap where I point',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '',
        route: '/dashboard',
        title: 'Welcome, Lisa',
        description: "On your phone you reach for six tools. I'll walk you to each — just tap where I point.",
      },
      {
        type: 'highlight',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        title: 'Quick book with +',
        description: 'This round + button books an appointment in seconds. The Calendar tutorial walks you through it.',
        placement: 'top',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-daily-log"]',
        title: 'Tap Daily Log',
        description: 'Every service performed today. Tap it to take a look.',
        placement: 'top',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-residents"]',
        title: 'Tap Residents',
        description: 'Everyone at the selected facility. Tap to open it.',
        placement: 'top',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-analytics"]',
        title: 'Tap Analytics',
        description: 'Revenue and stylist performance. Tap to see it.',
        placement: 'top',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-payroll"]',
        title: 'Tap Payroll',
        description: 'Pay periods, ready to review. Tap to open.',
        placement: 'top',
      },
      {
        type: 'click',
        selector: '[data-tour-mobile="mobile-home-logo"]',
        title: 'Tap the logo to go home',
        description: 'The Senior Stylist logo, top-left, always takes you back to your Calendar.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Deeper tools are on the website',
        description: 'Adding facilities, franchises, merging duplicates, the stylist directory, and QuickBooks setup live on the full site. Open seniorstylist.com on a computer for those.',
      },
    ],
    learnings: [
      'Tapped through Log, Residents, Analytics, and Payroll',
      'The + button books on the go',
      'The logo always returns you home; master-only tools are on desktop',
    ],
  },
  {
    id: 'scripted-master-calendar-mobile',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'click',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        route: '/dashboard',
        title: 'Tap + to book',
        description: 'The + button opens the booking form. Tap it.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        advanceSelector: '[data-tour="booking-modal-resident-option"]',
        title: 'Pick the resident',
        description: 'We typed "Smith" for you. Tap Mrs. Smith below to select her — or edit the search yourself.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set — price and duration fill in automatically.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Book it',
        description: 'Tap Book Appointment. A demo booking is created — not on your real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form with +',
      'Picked a resident, service, and time',
      'Saved the appointment',
    ],
  },
  {
    id: 'scripted-master-daily-log-mobile',
    title: 'Daily Log',
    scenarioSummary: 'Review what was done today',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-daily-log"]',
        route: '/log',
        title: 'Daily Log',
        description: 'Every completed service for the day, by stylist.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        title: 'A log entry',
        description: 'Each row is one appointment — resident, service, price, and payment status.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour-mobile="log-export-excel"]',
        title: 'Export to Excel',
        description: 'Download a styled spreadsheet matching your accounting format.',
        placement: 'bottom',
      },
    ],
    learnings: [
      'Read the daily log on mobile',
      'Understand a log entry',
      'Export logs to Excel',
    ],
  },
  {
    id: 'scripted-master-residents-mobile',
    title: 'Add a Resident',
    scenarioSummary: 'Add a new resident from your phone',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-search"]',
        route: '/residents',
        title: 'Find anyone fast',
        description: 'Type a name or room number here to jump straight to a resident.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-new-button"]',
        title: 'Tap + to add a resident',
        description: 'Opens the new-resident form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="residents-add-name"]',
        typeValue: 'Eleanor Davis',
        title: 'Name entered',
        description: "We typed a demo name. Use the resident's full name in practice.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-add-submit"]',
        title: 'Save the resident',
        description: 'Tap Add. A demo resident is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Imports & duplicates on desktop',
        description: 'Bulk CSV import and the duplicate-merge tool are on the full website — open it on a computer.',
      },
    ],
    learnings: [
      'Searched the resident list',
      'Added a resident on mobile',
      'Bulk import & merge live on desktop',
    ],
  },
  {
    id: 'scripted-master-analytics-mobile',
    title: 'Analytics',
    scenarioSummary: 'Check revenue and performance on the go',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-analytics"]',
        route: '/analytics',
        title: 'Analytics',
        description: 'Revenue and appointment trends for the selected facility.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-revenue-summary"]',
        title: 'Revenue summary',
        description: 'Total revenue, appointment count, and unpaid balance at a glance.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="analytics-date-range"]',
        title: 'Date range',
        description: 'Switch the month or pick a custom range.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Cross-facility view on desktop',
        description: 'Comparing all your facilities side by side is best on the full website.',
      },
    ],
    learnings: [
      'Read the revenue summary',
      'Change the date range',
      'Cross-facility analytics is on desktop',
    ],
  },
  {
    id: 'scripted-master-payroll-mobile',
    title: 'Payroll',
    scenarioSummary: 'Review pay periods and mark them paid',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-payroll"]',
        route: '/payroll',
        title: 'Payroll',
        description: 'Pay periods auto-generate from completed bookings.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="payroll-period-list"]',
        title: 'Pay periods',
        description: 'One per stylist per month — tap a period to see the earnings breakdown.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Mark paid & QuickBooks',
        description: "Open a period to see gross, tips, and net pay. Marking paid and pushing to QuickBooks work here too — the wider layout is easier on desktop.",
      },
    ],
    learnings: [
      'Find pay periods on mobile',
      'Read the earnings breakdown',
      'Mark a period paid',
    ],
  },
  {
    id: 'scripted-master-settings-mobile',
    title: 'Settings',
    scenarioSummary: 'Adjust facility settings from your phone',
    platform: 'mobile',
    role: 'super_admin',
    steps: [
      {
        // Settings lives in the nav "More" sheet by default (Phase 17) — no
        // stable tab to highlight, so this is an info step on the page itself.
        type: 'highlight',
        selector: '',
        route: '/settings',
        title: 'Settings',
        description: 'Facility details, hours, team, and integrations — find it under More in the bottom bar.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="settings-working-hours"]',
        title: 'Working hours',
        description: 'Set the days and times your facility operates — these bound the booking slots.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Facilities, franchises & billing on desktop',
        description: 'Adding facilities, franchise management, merging duplicates, and QuickBooks setup are on the full website. Open it on a computer for those.',
      },
    ],
    learnings: [
      'Where facility settings live',
      'Set working hours',
      'Master-only setup is on desktop',
    ],
  },
]
