import type { ScriptedTour } from './scripted-tour-types'

export const STYLIST_DESKTOP_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-stylist-getting-started-desktop',
    title: 'Getting Started',
    scenarioSummary: 'Quick tour of your sidebar',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="nav-calendar"]',
        route: '/dashboard',
        title: 'Your Calendar',
        description: 'Click here each morning to see your schedule — appointments, times, and residents.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="calendar-time-grid"]',
        title: "Today's schedule",
        description: 'Your appointments appear on this grid. Click any open slot to add a booking.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-daily-log"]',
        title: 'Daily Log',
        description: 'After each visit, confirm the service and mark payment here.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="checkin-banner"]',
        title: 'Check-in banner',
        description: 'Click when you arrive. Running late? Your appointments shift automatically.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="nav-my-account"]',
        title: 'My Account',
        description: 'Your schedule, hours, and profile. All set!',
        placement: 'right',
      },
    ],
    learnings: [
      'Found the Calendar for your daily schedule',
      'Found the Daily Log for confirming visits',
      'Learned about the check-in banner',
    ],
  },

  {
    id: 'scripted-stylist-calendar-desktop',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: 'Click an open time slot',
        description: 'Click any open slot on your calendar to start a new booking.',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below. Click Next.',
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-resident-option"]',
        title: 'Click Mrs. Smith',
        description: 'Click her name to select her.',
        placement: 'right',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Price and duration filled automatically. Click Next.',
        placement: 'right',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am. Click Next.',
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Save the booking',
        description: 'Click Book Appointment. A demo booking is created — not on your real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form from the calendar',
      'Selected a resident, service, and time',
      'Saved the appointment',
    ],
  },

  {
    id: 'scripted-stylist-daily-log-desktop',
    title: 'Daily Log',
    scenarioSummary: 'Mark Mrs. Smith as paid and finalize the day',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Your Daily Log',
        description: "Mrs. Smith's appointment is here. Confirm visits and mark payment after each one.",
      },
      {
        type: 'click',
        selector: '[data-tour="log-payment-toggle"]',
        title: 'Click the payment badge',
        description: 'Click the $ badge to mark Mrs. Smith as paid.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="log-payment-toggle"]',
        title: 'Marked paid',
        description: 'Billing updates automatically. Your bookkeeper sees this in real time.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'Finalize the day',
        description: 'Click Finalize Day to lock your log. Your admin and bookkeeper can see your completed day.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the appointment in the Daily Log',
      'Marked payment as paid',
      'Finalized the day',
    ],
  },

  {
    id: 'scripted-stylist-checkin-desktop',
    title: "I'm Here Check-In",
    scenarioSummary: 'Check in when you arrive at the facility',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="checkin-banner"]',
        route: '/dashboard',
        title: 'Check-in banner',
        description: 'Appears on days you have appointments. Click it when you arrive.',
      },
      {
        type: 'click',
        selector: '[data-tour="checkin-button"]',
        title: "Click 'I'm Here →'",
        description: 'Records your arrival time against your first appointment.',
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '[data-tour="calendar-time-grid"]',
        title: "You're checked in",
        description: 'Arrived late? We offer to shift your remaining appointments forward automatically.',
      },
    ],
    learnings: [
      'Found the check-in banner',
      'Recorded your arrival',
      'Learned about automatic late-arrival rescheduling',
    ],
  },

  {
    id: 'scripted-stylist-finalize-day-desktop',
    title: 'Finalize Your Day',
    scenarioSummary: 'Close out the daily log',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Review before closing',
        description: 'Check payment status, notes, and any cancellations before you finalize.',
      },
      {
        type: 'click',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'Click Finalize Day',
        description: "Locks today's log. Your admin and bookkeeper can now see your completed day.",
        placement: 'top',
      },
    ],
    learnings: [
      'Reviewed bookings before closing out',
      'Finalized the day',
    ],
  },

  {
    id: 'scripted-stylist-my-account',
    title: 'My Account',
    scenarioSummary: 'Explore your schedule and compliance documents',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="my-account-schedule"]',
        route: '/my-account',
        title: 'Your schedule',
        description: 'Each day shows your working hours. Tap any day row to edit or clear your hours for that day.',
      },
      {
        type: 'click',
        selector: '[data-tour="my-account-compliance-upload"]',
        title: 'Upload a compliance doc',
        description: 'Click Upload to attach a license or insurance certificate. Your admin gets an alert before anything expires.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="my-account-timeoff"]',
        title: 'Request time off',
        description: 'Submit a time-off request here — your calendar blocks automatically and your admin is notified.',
      },
    ],
    learnings: [
      'Found your schedule and working hours',
      'Uploaded a compliance document',
      'Submitted a time-off request',
    ],
  },

  {
    id: 'scripted-stylist-signup-sheet',
    title: 'Sign-Up Sheet Queue',
    scenarioSummary: 'Pick up a pending resident request',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="stylist-pending-panel"]',
        route: '/dashboard',
        title: 'Your pending requests',
        description: 'Facility staff log resident requests here. The system assigns them to you based on your schedule.',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Pending request card',
        description: 'Each card shows the resident, preferred service, and any notes. When a request is pending, click "Pick time →" to convert it into a real booking.',
      },
      {
        type: 'highlight',
        selector: '',
        title: 'Book from the queue',
        description: 'The booking modal opens with the resident and service pre-filled. Pick a time slot and click Book Appointment — the request is cleared from the queue.',
      },
    ],
    learnings: [
      'Found pending requests in the sign-up queue',
      'Reviewed a resident request',
      'Converted a request into a booking',
    ],
  },

  {
    id: 'scripted-stylist-residents',
    title: 'Managing Residents',
    scenarioSummary: 'Add a demo resident',
    platform: 'desktop',
    role: 'stylist',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: "Your facility's residents",
        description: 'Everyone at your facility — visit history, room numbers, and service notes.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-search"]',
        title: 'Search residents',
        description: 'Type a name or room number to quickly find someone in a large list.',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-new-button"]',
        title: 'Click + to add a resident',
        description: 'Opens the new-resident form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="residents-add-name"]',
        typeValue: 'Demo Resident',
        title: 'Name entered',
        description: "We typed a demo name. Use the resident's real full name in practice. Click Next.",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-add-submit"]',
        title: 'Save the resident',
        description: 'Click Add. The demo resident is auto-cleaned after the tour.',
        placement: 'top',
      },
    ],
    learnings: [
      'Found the residents list',
      'Searched for a resident',
      'Added a new resident',
    ],
  },
]
