import type { ScriptedTour } from './scripted-tour-types'

export const FACILITY_STAFF_TOURS: ScriptedTour[] = [
  {
    id: 'scripted-facility-staff-residents',
    title: 'Add a Resident',
    scenarioSummary: 'Add a new resident to your facility',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        route: '/residents',
        title: 'Your Residents list',
        description: 'Everyone at your facility — visit history and balances in one place.',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-new-button"]',
        title: 'Click + to add a resident',
        description: 'Opens the new-resident form.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="residents-add-name"]',
        typeValue: 'Eleanor Davis',
        title: 'Name entered',
        description: "We typed a demo name. Use the resident's full name in practice..",
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="residents-add-submit"]',
        title: 'Save the resident',
        description: 'Click Add. A demo resident is created — auto-cleaned up after the tour.',
        placement: 'top',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Resident added',
        description: "They're in your list. Open their profile to add room number, POA contact, and notes.",
      },
    ],
    learnings: [
      'Found the Residents list',
      'Created a new resident',
      'Ready to add room, POA, and notes',
    ],
  },

  {
    id: 'scripted-facility-staff-scheduling-desktop',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: 'Click an open time slot',
        description: 'Click any open slot on the calendar to start a new booking.',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below..',
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-resident-option"]',
        title: 'Click Mrs. Smith',
        description: 'Click her name to select her.',
        placement: 'right',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Price and duration filled automatically..',
        placement: 'right',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am. A stylist is auto-assigned..',
        placement: 'right',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Save the booking',
        description: 'Click Book Appointment. A demo booking is created — not on the real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form from the calendar',
      'Selected a resident, service, and time',
      'Stylist auto-assigned and appointment saved',
    ],
  },

  {
    id: 'scripted-facility-staff-scheduling-mobile',
    title: 'Book an Appointment',
    scenarioSummary: 'Book Mrs. Smith for a Wash & Set tomorrow at 10am',
    platform: 'mobile',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour-mobile="dashboard-new-booking-fab"]',
        route: '/dashboard',
        title: 'Start a new booking',
        description: 'Tap the + button to open the booking form.',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below..',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-resident-option"]',
        title: 'Tap Mrs. Smith',
        description: 'Tap her name to select her.',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-service"]',
        typeValue: '{{wash-and-set}}',
        title: 'Service selected',
        description: 'Wash & Set is set. Price and duration filled automatically..',
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="booking-modal-date"]',
        typeValue: '{{tomorrow-10am}}',
        title: 'Date and time set',
        description: 'Tomorrow at 10am. A stylist is auto-assigned..',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="booking-modal-submit"]',
        title: 'Save the booking',
        description: 'Tap Book Appointment. A demo booking is created — not on the real schedule.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the booking form',
      'Selected a resident, service, and time',
      'Stylist auto-assigned and appointment saved',
    ],
  },

  {
    id: 'scripted-facility-staff-signup-sheet',
    title: 'Use the Sign-Up Sheet',
    scenarioSummary: 'Log that Mrs. Smith wants a Wash & Set — no time slot needed',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-button"]',
        route: '/dashboard',
        title: 'Open the Sign-Up Sheet',
        description: "No time to pick a slot? Log the request here — a stylist will schedule it later.",
        placement: 'bottom',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-resident"]',
        typeValue: 'Smith',
        title: 'Resident filled in',
        description: 'We typed "Smith" — Mrs. Smith appears below..',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-resident-option"]',
        title: 'Click Mrs. Smith',
        description: 'Click her name to select her.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-service"]',
        typeValue: 'Wash',
        title: 'Service searched',
        description: 'We searched for Wash & Set. Click it in the list.',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-service-option"]',
        title: 'Select Wash & Set',
        description: 'Click to select the service.',
        placement: 'left',
      },
      {
        type: 'type',
        selector: '[data-tour="signup-sheet-preferred-date"]',
        typeValue: '{{tomorrow}}',
        title: 'Preferred date set',
        description: 'We set tomorrow. Helps auto-assign the right stylist..',
        placement: 'left',
      },
      {
        type: 'click',
        selector: '[data-tour="signup-sheet-submit"]',
        title: 'Add to the sheet',
        description: 'Click Add to Sheet. A stylist will convert this into a real booking.',
        placement: 'top',
      },
    ],
    learnings: [
      'Opened the Sign-Up Sheet',
      'Logged a resident, service, and preferred date',
      'Request queued for a stylist to schedule',
    ],
  },

  {
    id: 'scripted-staff-getting-started',
    title: 'Getting Started',
    scenarioSummary: 'Walk your front-desk workflow, start to finish',
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="calendar-time-grid"]',
        route: '/dashboard',
        title: "Your facility's calendar",
        description: "Every stylist's bookings at your facility, all in one place. This is your home base.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="signup-sheet-button"]',
        title: 'Take a request',
        description: 'When a resident asks for an appointment, log it here — the system auto-assigns the right stylist by date and service.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-residents"]',
        title: 'Open Residents',
        description: 'Look up and update residents. Click Residents.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="residents-table"]',
        title: 'Your residents',
        description: 'Names, rooms, and POA contacts. Add new residents as they move in, and update profiles here.',
        placement: 'bottom',
      },
      {
        type: 'click',
        selector: '[data-tour="nav-daily-log"]',
        title: 'Open the Daily Log',
        description: 'See the day unfold. Click Daily Log.',
        placement: 'right',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        title: 'Monitor the day',
        description: "Watch services get logged in real time — read-only for you, but a great end-of-day check that everything looks right.",
        placement: 'bottom',
      },
      {
        type: 'highlight',
        selector: '',
        title: "That's your workflow",
        description: 'Take requests → book on the calendar → keep residents current → review the log. The other tutorials go deeper on each.',
      },
    ],
    learnings: [
      'Take requests and book appointments',
      'Look up and update residents',
      'Review the daily log',
    ],
  },

  {
    id: 'scripted-staff-daily-log',
    title: 'The Daily Log',
    scenarioSummary: "Read today's appointments in the daily log",
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: "Today's appointments",
        description: 'Every service logged today — stylist, resident, service, and payment status.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="log-payment-toggle"]',
        title: 'Payment status',
        description: 'Each entry shows whether the service is paid, invoiced, or waived — set by the stylist.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="peek-resident-trigger"]',
        title: 'Peek at a resident',
        description: "Click any resident name to see their visit history and notes without leaving this page.",
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'Finalize button',
        description: "At end of day the stylist or admin locks the log. You'll see a green checkmark when it's done.",
      },
    ],
    learnings: [
      "Read today's daily log",
      'Understood payment status',
      'Peeked at a resident profile',
      'Learned about finalization',
    ],
  },

  {
    id: 'scripted-staff-daily-log-readonly',
    title: 'Daily Log (Read-Only)',
    scenarioSummary: "Monitor today's services as facility staff",
    platform: 'desktop',
    role: 'facility_staff',
    steps: [
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-entry-row"]',
        route: '/log',
        title: 'Facility staff view',
        description: 'You can see every appointment logged today — service, resident, stylist, and amount. All read-only.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="peek-resident-trigger"]',
        title: 'Peek at a resident',
        description: 'Click any resident name for a quick profile view — last visits, notes, and contact info.',
      },
      {
        type: 'highlight',
        selector: '[data-tour="daily-log-finalize-button"]',
        title: 'End-of-day finalization',
        description: "The Finalize button locks the day's log. Only admins and stylists can finalize.",
      },
    ],
    learnings: [
      'Monitored the daily log as facility staff',
      'Peeked at a resident profile',
      'Understood the finalization step',
    ],
  },
]
